"""
enums
"""
enum MaterialTypes {
  SKIN
  CALFSKIN
  BERYL
  WOLFRAMITE
  FLINT
  POLLUCITE
  WHALEBONE
  MAPLE
  GILT
  TEAK
  GUM_ELASTIC
  PEARL
  CAST
  FOSSILS
  FISH_SKIN
  BLACK_METAL
  RUBY
  BOXWOOD
  INSECT
  LAVENDER
  CANE
  FEATHER
  IVORY
  QUARTZ
  TOPAZ
  SELENITE
  HORN
  ROPE
  TORTOISESHELL
  PENICILLIN
  ROSEWOOD
  COFFINITE
  FRUITWOOD
  CALCITE
  MICA
  HUMAN_HAIR
  LIMESTONE
  HAIR
  GARNET
  BORAX
  RESIN
  FRUIT
  RUBBER
  SEEDS
  SILVER
  IRON
  BONE
  BRISTLE
  CARDBOARD
  DOWEL
  PLANT
  HESSIAN
  WALNUT
  ANODISED
  MARBLE
  MERCURY
  OAK
  HARDBOARD
  CANVAS
  FLUORSPAR
  BEECH
  BLUED
  LABRADORITE
  ALUMINIUM
  COTTON_WOOL
  CLAY
  LEATHER
  GOLD
  ANTHRACITE
  SILK
  ARAGONITE
  SOAPSTONE
  CHALK
  BASALT
  MOTHER_OF_PEARL
  OXIDISED
  PAPER
  WOOL
  BRONZE
  GRANITE
  DRIED_MOSS
  SHELL
  BLUE_JOHN
  GYPSUM
  SAPPHIRE
  SPODUMENE
  EBONY
  LIGNUM_VITAE
  WHITE_METAL
  ALABASTER
  MAHOGANY
  STEEL
  AMBER
  RAYSKIN
  FELDSPAR
  SUEDE
  COAL__CANNEL
  PHOSPHOR
  BACTUNG_METAL
  GUM_ARABIC
  CHROME
  PLATE
  SOLDER
  CRYSTAL
  BRONZED
  LEAF
  SATINWOOD
  COTTON
  LINEN
  BELL_METAL
  HARDWOOD
  LEAD
  COPPER
  FLOWER
  BRASS
  TOURMALINE
  PINE
  LIGNITE
  CORK
  BAMBOO
  SAND
  GRAPHITE
  PEARWOOD
  VELLUM
  SHAGREEN
  HIDE
  ALLOY
  PITCH
  MAGNESIUM_ALUMINATE
  TOOTH
  BASE_METAL
  MOULD
  ICELAND_SPAR
  EBONISED_WOOD
  CHIPBOARD
  SPONGE
  WAX
  RED_CRYSTAL
  LODESTONE
  STAINLESS
  COAL__BITUMINOUS
  SLATE
  NITRE
  ANTLER
  AGATE
  PEAT
  PIGSKIN
  RED_MINERAL
  GUNMETAL
  KERNITE
}

enum OccupationTypes {
  SHIPPER
  REGULATOR
  ASTRONOMER
  JOINER
  MARINER
  SPRINGER
  REFINER
  IRONMONGER
  BRIGHTSMITH
  MAKER__SCIENTIFIC_INSTRUMENTS
  CHANDLER
  FILE
  SCHOOLMASTER
  IMPORTER
  HATTER
  CHEMIST__OPERATIVE
  LAMPIST
  ADJUSTER
  GEOGRAPHER
  JAPANNER
  PROFESSOR
  AUCTIONEER
  COLOURMAN__ARTISTS_
  CLERGYMAN
  GOLDSMITH
  CUTLER
  MACHINIST
  SELLER__SCIENTIFIC_INSTRUMENTS
  PRACTITIONER
  STAINER
  OCULIST
  GUNSMITH
  DIALLIST
  WORKER
  MODELLER
  ASSAYER
  EXPORTER
  WRIGHT
  GRINDER
  ARCHITECT
  JEWELLER
  OPTICIAN
  SMITH
  CUTTER
  CONTRACTOR
  RESTAURANTEUR
  MINERALOGIST
  PHARMACIST
  WHOLESALER
  DEALER
  BROKER
  JOURNALIST
  DRAWER
  MATHEMATICIAN__NAVAL
  MALTSTER
  TINMAN
  OUTFITTER
  CARRIER
  GYMBLER
  PLATER
  MACHINEGRAPHIST
  OILMAN
  ELECTRICIAN__MEDICAL
  SURVEYOR
  MATHEMATICIAN
  BRAZIER
  GAS_FITTER
  STOPPERER
  HABERDASHER
  PUBLISHER
  FELLOW
  WHITESMITH
  PAINTER
  CHAIRMAN
  AURIST
  UPHOLSTERER
  MECHANICIAN
  PRESSER
  BLOWER
  BAKER
  OUTFITTER__LABORATORY
  POSTMASTER
  BRICKLAYER
  POLISHER
  DECORATOR__HOUSES
  BOOKKEEPER
  FRAMER
  MERCHANT
  LOCKSMITH
  STATIONER
  GILDER
  MANAGING_DIRECTOR
  MECHANIST
  DIVIDER
  DRAUGHTSMAN
  GARDENER
  PLOUGHWRIGHT
  WRITER
  HAWKER
  CORRECTOR
  LECTURER
  TEACHER
  SALESMAN
  TOYMAN
  METALLURGIST
  MINIATURIST
  ARTIST__PHILOSOPHICAL
  ENGRAVER
  COLOURER
  BARRISTER
  COPPERSMITH
  CHEESEMONGER
  PAINTER__PORTRAIT
  GALVANIST
  ELECTRICIAN
  CHEMIST
  ENAMELLER
  INVENTOR
  NATURALIST
  ASSAY_MASTER
  GAUGER
  FACTOR
  ARTIST
  LITHOGRAPHER
  MILLWRIGHT
  PHYSICIAN
  ROLLER
  MONEY_CHANGER
  FINISHER
  MOUNTER
  PEWTERER
  CHANDLER__SHIP
  SILVERSMITH
  PERFUMER
  GENTLEMAN
  HYDROGRAPHER
  ENGINEER
  JOURNEYMAN
  SCALEMAKER
  WAREHOUSEMAN
  BUILDER
  COACHBUILDER
  VICTUALLER
  FOUNDER
  PROVIDER
  BOATBUILDER
  BAR_FITTER
  MICROSCOPIST
  DESIGNER
  PHOTOGRAPHER
  MAP_ROLLER
  FORGER
  HAMMERMAN
  BEATER
  MATHEMATICIAN__MILITARY
  TAILOR
  FILTER
  BREWER
  ASSISTANT
  DECORATOR
  MANAGER__FINANCIAL
  WATCHMAKER
  WHEELWRIGHT
  COOPER
  BELL_HANGER
  DENTIST
  JUDGE
  GALVANIST__MEDICAL
  SHOPKEEPER
  SUPPLIER
  SINKER
  RESTORER
  THEOLOGER
  CONFECTIONER
  POTTER
  DRAPER
  GANGSMAN
  PAWNBROKER
  MECHANIC
  HARDWAREMAN
  REVENUE_OFFICIAL
  ENGINEER__ELECTICAL
  AUTHOR
  ELECTRO_PLATER
  MAGNETICIAN
  PLUMBER
  FLOUR_MAN
  LAPIDARY
  PRINTER
  MANUFACTURER
  CARVER
  CARTOGRAPHER
  TOBACCONIST
  CAPTAIN
  AGENT
  DRUGGIST
  SCULPTOR
  CARPENTER
  MANAGER
  BOOKSELLER
  COLLECTOR
  BLACKSMITH
  ARTIST__PHOTOGRAPHIC
  TURNER
}

enum FreedMode {
  PURCHASE
  EXAMINATION
  PATRIMONY
}

enum Nationalities {
  BELGIAN
  ITALIAN
  FRENCH
  SPANISH
  AMERICAN
  DANISH
  INDIAN
  POLISH
  RUSSIAN
  GERMAN
  DUTCH
  SWEDISH
}

enum Religions {
  JEWISH
  QUAKER
  FREE_CHURCH
  SWEDENBORGIAN
}

enum SubjectAreas {
  CHEMISTRY
  ACCOUNTS
  NAVIGATION
  FILM
  CINEMATOGRAPHY
  NATURAL_PHILOSOPHY
  ASTRONOMY
  TELEGRAPH
  PHOTOGRAPHY
  ELECTRICAL
}

enum MembershipType {
  COUNCIL_MEMBER
  HONORARY_MEMBER
  FOUNDER_MEMBER
  VICE_PRESIDENT
  FELLOW
  MEMBER
  JOURNEYMAN
  CROWN_AGENT
  MASTER
  PRESIDENT
  ASSISTANT
  WARDEN
}

enum SourceTypes {
  OBSERVATION_RECORD
  RATE_BOOK
  REGISTER
  LEARNED_SOCIETY_RECORD
  TAX_RETURN
  LIVERY_COMPANY_RECORD
  CATALOGUE
  PARISH_RECORD
  POLL_BOOK
  BAPTISM_RECORD
  ARCHIVAL_DOCUMENT
  CENSUS_RECORD
  ADVERTISEMENT
  PERIODICAL
  ONLINE_RESOURCE
  ORGANISATION_RECORD
  PATENT
  TRIAL_RECORD
  WILL
  AUCTION_CATALOGUE
  BIRTH_CERTIFICATE
  BURIAL_RECORD
  TRADE_CARD
  EXHIBITION_CATALOGUE
  CENSUS_ENTRY
  BOOK
  DEATH_CERTIFICATE
  GAZETTEER_ENTRY
  LECTURE_NOTES
  CALENDAR
  DICTIONARY
  COLLECTION_RECORD
  DIRECTORY
  LETTER
  BANKRUPTCY_PROCEEDINGS
  MARRIAGE_RECORD
  MAP
}

enum AwardTypes {
  MEDAL
  GRAND_PRIX
  GOLD_MEDAL
  COPLEY_MEDAL
  BRONZE_MEDAL
  SILVER_MEDAL
  HONOUR
}

enum TypesofLegalProcess {
  PETITION
  PROBATE
  PATENT
  PROSECUTION
}

enum ConfidenceType {
  UNCERTAIN
  FUZZY
}

enum AddressFunctionTypes {
  TESTING_STATION
  COUNTRY_RESIDENCE
  FACTORY
  AGENCY
  PRIMARY_OUTLET
  MULTIPLE_OCCUPANCY
  SUBSIDIARY
  RESIDENCE
  SCHOOL
  ADDITIONAL_OUTLET
}

enum InventionTypes {
  SOLE_MAKER
  CLAIMED
  MADE
}

enum FreedCategory {
  BROTHER
  LOOSE
}

enum ObjectTypes {
  MODEL__CAM_AND_BEAM
  MEASURE__CORN
  BALANCE__PRECISION
  BAROMETER__MERCURY
  SUNDIAL__MECHANICAL_EQUINOCTIAL_DIAL
  LEVEL__DRAINAGE
  DISCHARGE_TUBE__DE_LA_RIVE
  ELECTROMAGNET
  THERMOMETER__BREWER_S
  MECHANICAL_INTEGRATOR__AMSLER
  LENS__MOUNTED
  GLOBE__DISSECTED
  HYGROMETER__DANIELL
  EUDIOMETER
  OPTHALMIC_INSTRUMENT
  SPECTROGRAPH
  PLATE_MEASURER
  ASTRONOMICAL_EQUIPMENT
  HYDROMETER
  MICROSCOPE_ACCESSORY
  PNEUMATICS
  FOCOMETER
  SPECTROSCOPE__ULTRA_VIOLET
  SEA_CHART
  THEODOLITE__SIMPLE
  REFLECTING_CIRCLE
  LAMP__ELECTRIC
  SPECTACLES__TEMPLE
  EXTENSOMETER
  PROJECTION_APPARATUS
  ADAPTOR
  ELECTRICAL_MACHINE
  SUNDIAL__DAY_NIGHT_DIAL
  SINKING_BOWL_TIMER
  BURNING_GLASS
  HYDROMETER__RECORDING
  MALLET
  BATTERY__VOLTAIC_PILE
  SUNDIAL__AZIMUTH_DIAL
  CLOCK__PENDULUM
  PROPORTIONAL_DIVIDERS
  SET_SQUARE
  GAUGE_GLASS
  CLOCK
  ELECTROSTATIC_GENERATOR__VOSS
  PROTRACTOR__DRAFTING
  PROTECTIVE_GLASSES
  CHEMICAL_APPARATUS
  OCTANT
  TAILOR_S_SQUARE
  ELECTROMETER
  DRAWING_BOARD
  BAROGRAPH
  GLOBE__LUNAR
  DYNAMOMETER
  DIP_CIRCLE
  GALVANOMETER__TANGENT
  PRISM__ADJUSTABLE
  PEDOMETER
  SOUND_CONE
  TRANSIT_INSTRUMENT
  COMPASS_NEEDLE
  CHLADNI_PLATE_CLAMP
  BUZZER
  WATCH
  LEYDEN_JAR
  MILITARY_INSTRUMENT
  ASTRO_EQUATORIAL_INSTRUMENT
  HYGROMETER__TWIRLING
  GAUGE__RAIN
  OPTICAL_GLASS
  CAMERA__STEREOGRAPHIC
  COURSE_INDICATOR
  STROH_S_VOWEL_SOUNDER
  COMPASS__TRIANGLE
  WEIGHING_MACHINE
  ENGINE__BEAM
  HYDROMETER__DICAS
  ELLIPSOGRAPH
  THERMOMETER__KINNERSLEY
  COELOSTAT
  SLIDE_RULE__COGGESHALL
  TOOL
  BAROMETER__PORTABLE
  EARTH_INDUCTOR
  SUNDIAL__EQUINOCTIAL_RING_DIAL
  MECHANICAL_INTEGRATOR
  LEVEL__DUMPY
  LEVEL__BUREL
  LAMP__GALVANOMETER
  THEODOLITE__EVEREST
  MIRROR_GRINDER
  SIREN__CAGNIARD
  CLOCK__TIME_SYSTEM
  GNOMON
  WEIGHTS__NESTED
  CINEMATOGRAPH_PROJECTOR
  KINORA
  COMPASS__BEAM
  TABLE
  LIGHTNING_DEMONSTRATOR
  SIREN__ELECTRICAL
  ELECTROMAGNET_FOR_STRING_GALVANOMETER
  BAROMETER__WATCH_ANEROID
  TACHEOMETER
  CABLE
  QUADRANT
  BURNER__GOBLET
  LENS__BICONVEX
  OPERA_GLASSES
  MAGNET__COMPOUND
  COMETARIUM
  TELESCOPE__ACHROMATIC
  BURETTE__BINK
  MIRROR__LIGHT_RECOMBINATION
  GYROCOMPASS
  CHRONOMETER__MARINE
  HYDROMETER__FAHRENHEIT
  STANDARD_CELL
  PULLEY_ACCESSORY
  SUNSHINE_RECORDER
  PEN
  SHUNT
  THEODOLITE
  GALVANIC_APPARATUS
  PRINTING_PLATE_FOR_PAPER_SLIDE_RULE
  BALANCE__APOTHECARY_S
  ELECTRICAL_MACHINE__CLARKE
  CURVOGRAPH
  CLOCK__REGULATOR
  HYGROMETER__EDNEY_PAPER
  ANEMOMETER__LOWNE
  RULE__PLOTTING
  CAMERA_LUCIDA
  DISCHARGE_TUBE__PERRIN
  SEXTANT__HEZZANITH
  QUADRANT__ASTRONOMICAL
  PERSPECTIVE
  COMPASS_CORRECTOR
  ESCAPEMENT__DETACHED_LEVER
  RESISTANCE_BOX
  STEREOSCOPE__POCKET
  STAND__THERMOMETER
  SUNDIAL__POCKET
  METEOROLOGICAL_INSTRUMENT
  SUNDIAL__BUTTERFIELD_DIAL
  CARBON_ARC_LAMP__BROCKIE
  ECHO_SOUNDER
  OBJECTIVE
  RULE__ROUTLEDGE
  DOTTING_INSTRUMENT
  BAROMETER__FARMER_S
  BALANCE__POSTAL
  MICROMETER_PART
  BORDA_CIRCLE
  SHIP_S_TELEGRAPH
  MATHEMATICAL_INSTRUMENT
  OPTOMETER
  CINEMATOGRAPH_MECHANISM
  GONIOMETER__CONTACT
  RULE__GUNNER_S
  SPECTROPHOTOMETER
  SLIDE_RULE__MANNHEIM
  SOUNDING_LEAD
  ELECTRIC_MACHINE
  WRAP_REEL
  MEASURE__BARREL
  SPARK_GAP
  AMPUTATION_SET
  CALENDAR__MERIDIAN
  COMPASS__GUNTER_S_CALLIPERS
  MERCURY_DIFFUSING_CUP
  POLEMOSCOPE
  PULLEY
  FURNITURE
  EUDIOMETER__CAVENDISH
  WIND_SPEED_INDICATOR
  LEVEL__ENGINEER_S
  LANTERN_SLIDE
  FLASK__ROUND_BOTTOMED
  MORTAR
  MODEL__VERTICAL_MOTION
  MICROSCOPE__HYDRO_OXYGEN
  DIFFRACTION_GRATING__MOUNTED_ON_PRISM
  STAND__INSULATING
  LINEAR_DISTANCE_MEASURING_DEVICE
  RULE__HATTER_S
  AIR_PUMP__TATE
  LENS
  CURRENT_METER
  SUNDIAL__DOUBLE_HORIZONTAL_DIAL
  CLOCK__ASTRONOMICAL
  INDUCTION_COIL__MEDICAL
  MICROSCOPE__COMPOUND__WITH_MICRO_SPECTROSCOPE
  BAROMETER__POCKET_ANEROID
  MICROMETER__WIRE
  TRANSIT_CIRCLE
  GALVANOMETER_PART
  BALL_COCK
  MICRO_GALVANOMETER
  BURNER__BUNSEN
  NAVIGATIONAL_INSTRUMENT
  ALTIMETER
  HELIOSTAT__SILBERMANN
  CHLADNI_PLATE
  SIGNAL_INDICATOR
  HELIOCHRONOMETER
  MEASURE__BUSHEL
  CLINOMETER_RULE
  PLANIMETER
  TOY
  SPECTROSCOPE__PROJECTION
  GALVANOMETER__WILBERFORCE
  MULTIPLYING_GLASS
  ELECTRIFYING_MACHINE
  RULE__VERNIER
  REGENERATIVE_FURNACE
  ESCAPEMENT__SINGLE_PIN
  BAROMETER__ANEROID
  TRACHEOMETER
  STANDARD_LENGTH__METRIC
  WATER_MILL_PUMP
  CAMERA__PHOTOGRAPHIC
  PHYSICAL_APPARATUS
  SURGICAL_INSTRUMENT
  SLIDE_RULE__CIRCULAR
  GEISSLER_TUBE
  WIRELESS__RADIO__INSTRUMENT
  MAGIC_LANTERN__THE_TERPUASCOPE
  COMPASS_SIGHTS
  LAMP__OXY_HYDROGEN
  WATER_STERILISER
  PROTRACTOR__REFLECTING
  DOCUMENT
  BOTTLE__CHEMICAL
  PHOTOMETER__BUNSEN
  BINOCULAR_EYEPIECE_FOR_MICROSCOPE
  GLUCOMETER
  MODEL__PISTON
  PNEUMATIC_APPARATUS
  THEODOLITE__PLAIN__ALTAZIMUTH
  CHRONOMETER
  RULE__MATHEMATICAL
  PITH_BALL_STAND
  DIPLEIDOSCOPE
  BAROMETER__MARINE
  GAUGING_INSTRUMENT
  EYE_PROTECTOR
  LENS__CAMERA
  ORGAN_PIPE_BLOCK
  PANORGANON
  THERMOMETER__BRINE_PIPE
  LONGITUDE_SCALE
  COMPASS__MARINER_S
  ELECTROSTATIC_GENERATOR__HARRIS
  POLARISCOPE__SOLEIL
  STANDARD_METRE
  INHALER
  MICROSCOPE_SLIDE
  GLOBE__CELESTIAL
  SLIDE_RULE__POLLIT_S_PIPE_CALCULATOR
  POLARISCOPE__ELBOW
  STAND_WITH_SCREW_CLAMP
  LABORATORY_GLASSWARE
  HELICOGRAPH
  ELECTROSTATIC_GENERATOR
  OPHTHALMOSCOPE
  MAGNETIC_NEEDLE__PIVOTED
  ACOUSTICS_INSTRUMENT
  STOOL
  MIRROR__ROTATING_CUBIC
  HYDRAULIC_INSTRUMENT
  MANOMETER__DOUBLE_BULB
  SUNSHINE_RECORDER__CAMPBELL_STOKES
  PHOTOGRAPHIC_ACCESSORY
  SPECTROMETER
  MOMENTS_DEMONSTRATION_APPARATUS
  ENGINE__STEAM
  YARN_TESTING_LENS
  WHIRLING_TABLE
  THERMOMETER__BECKMANN
  PRINTING_PLATE
  MOONDIAL__HORIZONTAL
  ANAMORPHOSCOPE
  SYMPIESOMETER
  SUNDIAL__DIPTYCH_DIAL
  REGULATOR__OBSERVATORY
  PANTOMETRON
  LAMP__MAGNESIUM
  TINTOMETER
  BALANCE__INDUCTION
  CHART_WEIGHT
  CALCULATING_RULE
  CROSS_STAFF_HEAD
  ELECTROMETER__QUADRANT__DOLEZALEK
  GAUGE__DEPTH
  CLINOMETER
  THEODOLITE__TRANSIT
  COMPASS__MARINER_S__RECORDING
  GALVANOMETER__ASTATIC
  PRISM__NICOL
  HYDROSTATIC_MACHINE
  ELECTROLYSIS_APPARATUS
  SPECTROSCOPE
  BATTERY__DANIELL
  WAVEMETER
  STEELYARD__BISMAR_
  RAILWAY_CURVE
  MANOMETRIC_FLAME_APPARATUS_PART
  BATTERY_JAR
  MERIDIAN_CIRCLE
  DISCHARGE_TUBE__HITTORF_SPIRAL
  COMPASS__AZIMUTH
  CAMERA__LUZO
  THERMOMETER_PART
  SLIDE_RULE__SPIRAL
  MICROSCOPE__TRAVELLING
  ENCYCLOLOGIUM
  PEN__RULING
  PRISM__RIGHT_ANGLED
  STAND
  SPECTROSCOPE__TABLE
  MIRROR__BURNING
  SEXTANT__DRUM
  COMPASS__WING
  COURSE_CORRECTOR
  STANDARD_PINT
  SHIP_S_LOG__MECHANICAL
  THERMOMETER__SOLAR_RADIATION
  MARINE_EQUIPMENT
  MICROSCOPE__MARTIN
  TELESCOPE_PART
  CHART
  MARINER_S_JOURNALET
  SPECTACLES_PART
  HYDROMETER__O_TOOLE
  GAUGE__TIDE
  QUINTANT
  MODEL__OPTICAL
  ELECTROMETER__HARRIS_UNIT_JAR
  SPARK_GENERATOR
  POLE_INDICATOR
  CALORIMETER__JOLY_STEAM
  LENS_SYSTEM
  SPARK_CHAMBER
  PAPERWEIGHT
  HYGROMETER__MASON__VENTILATED
  TAPE_MEASURE__SURVEYOR_S
  AIR_PUMP__DOUBLE_BARREL__FLEUSS
  WIND_DIRECTION_INSTRUMENT
  PENDULUM
  HYDROSTATIC_APPARATUS
  RHEOSTAT
  SHIP_S_LOG_REGISTER
  PHONOGRAPH
  SCALE_BEAM
  SUNDIAL__CYLINDRICAL_DIAL
  DISCHARGE_TUBE__HOLTZ_VALVE
  SPECTROGRAPH__SOLAR
  NAVIGATION_SCALE
  ATWOOD_MACHINE__RIBBON
  CHRONOMETER__POCKET
  STANDARD_LENGTH__IMPERIAL
  MANOMETRIC_FLAME_APPARATUS__TROMBONE
  SPECIFIC_GRAVITY_APPARATUS
  VOLTMETER__UNIPIVOT
  PHOTOMETER__JOLY
  BALANCE__SPRING
  SEXTANT__DOUBLE
  MICROMETER_EYEPIECE
  CAMERA
  LAMP__DAVY
  QUADRANT__CROSS_BOW
  SPECTROSCOPE__DIRECT_VISION__MCCLEAN
  GALVANOMETER_SCALE
  LEVEL__TELESCOPIC
  COMPASS__AMPLITUDE
  GALVANOMETER__DEAD_BEAT_MIRROR
  INCUBATOR
  MANOMETRIC_FLAME_APPARATUS__CAPSULE
  WEIGHBRIDGE
  MODEL__DOUBLE_CRANK_SHAFT
  SUNDIAL__COMPASS_DIAL
  CALCULATOR__TEXTILE
  MICROSCOPE_PART
  PIEZOMETER
  ELECTRIC_TELEGRAPH
  GLOBE__PAPER
  MODEL__BOILER
  LAMP__DOBEREINER
  CAMERA__DETECTIVE
  CALCULATOR
  SIDEROSTAT
  MODEL__GRIDIRON_PENDULUM
  WEATHER_STATION
  TELEPHONE__FIELD
  SCIOPTIC_BALL
  SQUARE__FOLDING
  SHUNT__UNIVERSAL
  LORRAIN_GLASS
  WEIGHTS
  FLASK
  RULE__SHOES
  ELECTRICAL_SYSTEM_FOR_SYNCHRONISING_CLOCKS
  MECHANICAL_FINGER_FOR_MICROSCOPE
  SLIDE_RULE__BREWER_S
  STEELYARD
  LEVEL__Y
  BURNER
  ALIDADE__TELESCOPIC
  HYDRAULIC_INSTRUMENT_PART
  APPARATUS_FOR_TRAINING_THE_OCULAR_MUSCLES
  BATTERY_CELL
  CINEMATOGRAPH_PART
  OSCILLOGRAPH__DUDDELL
  CAMERA__BOX
  STROBOSCOPE__DRYSDALE_S
  MODEL__SPIRAL_AND_COG_WHEEL
  MODEL__RAILWAY_SIGNAL_LEVERS
  RACE_GLASSES
  LENS_GRINDING_MACHINERY__WATER_POWERED
  MICROSCOPE_STAGE_WITH_THERMOSTAT
  CLOCK__SIDEREAL
  LENS__CYLINDRICAL
  LAMP__LIME_LIGHT
  GAS_METER
  QED_COURSE_CORRECTOR
  ATWOOD_MACHINE
  ELECTROMETER__TORSION
  TRIPOD
  BATTERY__WOLLASTON
  EYEGLASSES
  BOTTLE__WOULFF
  GAUGE
  DIVIDING_INSTRUMENT
  HYGROGRAPH
  DISCHARGE_TUBE__SPIRAL
  MICROSCOPE__PROJECTING
  SPECTROSCOPE__ASTRONOMICAL
  BURETTE__MOHR
  SPECTACLES__INVISIBLE
  REPEATING_CIRCLE
  TELESCOPE__REFLECTING
  ESCAPEMENT__SPRING_DETENT
  MODEL__GIRDER_BRIDGE
  STEREOSCOPE
  RULE__JOINT
  TELESCOPE__BINOCULAR
  MERCURY_TROUGH
  KOHLRAUSCH_BRIDGE
  RULE__ROLLING
  BALANCE__ASSAY
  BAROMETER__MINE
  VISCOMETER
  CROSS_HEAD
  MODEL__STEAM_ENGINE
  ACCESSORY
  BACKSTAFF
  MAGNETOMETER__SUSPENSION
  CAMERA__FOLDING
  MODEL__ARCHIMEDES__SCREW
  CHEMICAL_INSTRUMENT
  SUNDIAL__ASTRONOMICAL_DIAL
  DISCHARGE_TUBE__GOLDSTEIN
  ELECTRIC_BELL___THE_GAMUT_
  BALANCE__ROBERVAL
  MEASURE__HALF_BUSHEL
  QUADRANTAL_PLANETARIUM_MACHINE
  SACCHARIMETER__JELLETT
  BATTERY__LECLANCH_
  PHILOSOPHICAL_APPARATUS
  ELECTROMETER__CUTHBERTSON_DISCHARGE
  SECTOR__ISOGRAPH
  FLASK__CYLINDER
  PLANE_TOOL
  ZENITH_SECTOR
  CAMERA__STEREOSCOPIC
  MODEL__VERNIER
  SURVEYING_INSTRUMENT__UNIVERSAL
  TUNING_FORK_STAND_WITH_ELECTROMAGNET
  BARLOW_GLOBE
  MODEL__REVOLVING_CROSS
  GAUGE__WATER
  TIMEPIECE
  DISCHARGE_TUBE__SPANGLED_AURORA
  MICROSCOPE__DRUM
  SUNDIAL__ANALEMMATIC_DIAL
  MEASURING_INSTRUMENT
  PROTRACTOR__RECTANGULAR
  CORK_BORER
  COLLIMATOR
  SONOMETER
  MELDOMETER__JOLY
  STOPWATCH
  MAGNETO_ELECTRIC_MACHINE
  WIND_DIAL
  CONDENSER__VARIABLE__AEPINUS
  DISCHARGE_TUBE
  ORGAN_PIPE_MOUTHPIECE
  BAROMETER__STICK
  COMPASS__CHARM
  GAUGE_TUBE
  WHEEL_CUTTING_ENGINE
  DIALLING_SCALE
  GEOMETRIC_SOLID
  TITRATION_APPARATUS
  GALVANOMETER__DEFLECTION
  PROTRACTOR__CIRCULAR
  TELLURION
  AMMETER__MAGNETO_STATIC
  MURAL_CIRCLE
  THERMOMETER_SCALE
  COMPASS__SIGHTING
  TELESCOPE__REFRACTING__PORTABLE_
  OPTICAL_MEASURING_INSTRUMENT
  COMPASS__OVERHEAD
  ELECTROMAGNETIC_INDUCTION_APPARATUS
  BATTERY__BUNSEN
  SLIDE_WIRE_BRIDGE
  ORRERY
  BALANCE__SPECIFIC_GRAVITY
  MIRROR__ROCKING
  SPECTROSCOPE__DIRECT_VISION__GRACE
  SPECTROSCOPE__PHOTOGRAPHIC
  HYGROMETER__DINES
  MODEL__STEAM_LOCOMOTIVE
  MODEL__ARC_MOTION
  GONIOMETER__SEARL
  GONIOMETER__CRYSTAL
  POCKET_MAGNIFIER
  FOOT_MEASUREMENT_DEVICE
  BATTERY__GROVE
  PSYCHROMETER
  TACHOMETER
  SPIROMETER
  HYGROMETER__SAUSSURE
  COMPASS
  WATER_FILTER
  KYMOGRAPH
  POLARIMETER
  RULE__SURVEYING
  SACCHARIMETER
  GALVANOMETER__UNIPIVOT
  CIRCUMFERENTOR
  MIRROR
  LAMP__GAS
  MEASURE__LIQUID
  ANALEMMA
  BATTERY__FLOATING
  SUNDIAL__VERTICAL_DIAL
  BURNER__OIL
  GALVANOMETER__DETECTOR
  RULE
  LACTOMETER
  TESLA_COIL_APPARATUS
  MODEL__MECHANICAL
  URINOMETER
  CAMERA__WET_PLATE
  MODEL__PUMP
  BATTERY__SMEE
  CAMERA__FALLING_PLATE
  BALANCE__HYDROSTATIC
  MICROSCOPE__COMPOUND
  GALVANOMETER
  POSITION_FINDER
  THERMO_HYGROGRAPH
  WEATHER_VANE
  MANOMETER
  THEODOLITE__PLAIN
  RANGEFINDER
  GALVANOMETER_LAMP_HOUSING
  MICROSCOPE__BINOCULAR
  WHISTLE
  CLOCK__TIDAL
  DYNAMETER
  HYDRAULICS
  PANTOGRAPH
  LAMP__MINER_S
  COMPASS__DRAG
  QUADRANT__GUNNER_S
  WEATHER_RECORDER
  SUNDIAL__MECHANICAL_DIAL
  BATTERY__DRY_PILE__ZAMBONI
  PRISM__CONICAL
  MODEL__LIFT_PUMP
  SUNDIAL__UNIVERSAL_DIAL__PORTABLE_
  LOGARITHMIC_CALCULATING_INSTRUMENT
  SOUNDING_LOG
  LENS_MEASURER
  TELESCOPE__ASTRONOMICAL
  AIR_FLOW_METER
  PYROMETER__DANIELL
  PHOTOMETER
  LAMP__SODIUM
  THERMOMETER__SELF_REGISTERING
  PROTRACTOR
  BALANCE__GUNNER_S
  MODEL__PHILOSOPHICAL
  SEISMOLOGY_INSTRUMENT
  TELESCOPE__DAY_AND_NIGHT
  ELECTROMETER__QUADRANT__THOMSON
  TELESCOPE__EQUATORIAL
  HYDROSTATIC_BUBBLE
  TRANSIT_INSTRUMENT__PORTABLE
  TELEGRAPHIC_INSTRUMENT
  LEAN_DIAL
  ELECTROMETER_PART
  TELEGRAPH_WIRE
  SUNDIAL__POLYHEDRAL_DIAL
  MICROSCOPE_MICROMETER
  MARINE_GLASSES
  ENGINE_INDICATOR
  CLOCK__TIMEZONE
  TELESCOPE__REFRACTING
  MICROSCOPE__BOTANICAL
  VARIATION_INSTRUMENT
  COMPENDIUM
  MODEL__COG_WHEELS
  SECTOR__POLAR
  ESCAPEMENT__CHRONOMETER
  GAUGE__MILL_GEAR
  WATER_PUMP
  AMMETER
  MODEL__DOMESTIC_WATER_SYSTEM
  COMPASS__VARIATION
  STEELYARD__POCKET
  MECHANICAL_APPARATUS
  MICROSCOPE_LANTERN
  SEXTANT__POCKET
  THERMOGRAPH__PHOTOGRAPHIC
  BURNER__SPIRIT
  QUADRANT__ELTON_S
  ARMILLARY_SPHERE
  DIVIDING_ENGINE
  INTEGRATOR
  ELECTROSTATIC_GENERATOR__DE_WINTER
  BAROMETER
  MOVEMENT
  HYGROMETER__REGNAULT
  ELECTRIC_BELL
  BAROGRAPH__DINE_S_FLOAT
  COMPASS_CARD__LIQUID
  SURVEYING_INSTRUMENT__POCKET
  WIND_INDICATOR
  DISCHARGE_TUBE__SPANGLED
  PLANISPHERE
  MODEL__REVOLVING_CYLINDER
  COMPASS_ROSE
  PRINTING_MACHINE
  PYROMETER
  ELECTROSTATIC_GENERATOR__HOLTZ
  CINE_PROJECTOR
  SUNDIAL__QUADRANT_DIAL
  CROSS_STAFF_PART
  LENS_HOLDER
  TAPE_MEASURE
  METER_INDEX
  MANOMETRIC_FLAME_APPARATUS
  PERSPECTOGRAPH
  THERMOMETER
  BULL_S_EYE_ILLUMINATOR
  CINE_CAMERA
  MAGNIFIER
  MIRROR__ANAMORPHIC
  ENGINE
  GALVANOMETER__ASTATIC_MIRROR
  ELECTROMAGNETIC_GENERATOR
  THERMOMETER__SPIRIT
  SLIDE_RULE__POWER_AND_SPEED_SCALE
  BALANCE__MARQUOIS
  ALMANAC
  SURVEYOR_S_WHEEL
  LAMP__PENTANE
  STEREOSCOPE__BREWSTER
  GAS_APPARATUS
  SIREN
  WEATHER_GLASS
  MODEL__MATHEMATICAL
  CLOCK__MARINE
  MEASURING_CYLINDER
  HYGROMETER__RECORDING
  MODEL__CLOCK_ESCAPEMENT
  THERMO_ELECTROMAGNET
  LEVEL__ABNEY
  ELECTROSTATIC_GENERATOR__RAMSDEN
  POLARISCOPE__TOURMALINE
  BATTERY__EDISON_LELANDE
  BATTERY
  WEIGHING_MACHINE__HYDROSTATIC
  PLANETARIUM
  MEDICAL_PHOTOGRAPH
  PLOTTING_SQUARE
  MAGNET
  GALVANOMETER__UPRIGHT
  MAGNIFYING_GLASS
  MECCA_DIRECTION_FINDER
  ASTROLABE__MARINER_S
  GAUGE__WATCHMAKER_S
  SEXTANT__SURVEYING
  GALVANIC_INSTRUMENT
  ROLLER_FOR_INCLINED_PLANE
  CYLINDER_ELECTRICAL_MACHINE
  GALVANOMETER__MIRROR
  GLOBE__POCKET
  OPTICAL_COMPARATOR
  ASTROSCOPE
  POLARISCOPE__DUBOSCQ
  RADIO_EQUIPMENT
  FLUXMETER
  AIR_PUMP__DOUBLE_BARREL
  SOUND_CYLINDER
  MANOMETRIC_FLAME_APPARATUS__BURNER
  SUNDIAL__INCLINING_DIAL
  BAROMETER__FORTIN
  GALVANOMETER__D_ARSONVAL
  AIR_PUMP__SYRINGE
  EUDIOMETER__URE
  PRISM__MULLER
  STOP_CLOCK
  MIRROR__REFLECTING
  MODEL__MICROMETER_SCREW
  GLOBAL_POSITIONING_SYSTEM
  SEISMOGRAPH
  QUADRANT__HORARY
  PHOTOGRAPHY_EQUIPMENT
  COIN_CALENDAR
  BOTTLE__ACID
  CRUCIBLE
  LENS__CONCAVE_CONVEX
  SEXTANT
  HYDROMETER_WEIGHT
  MICROTOME
  PNEUMATIC_INSTRUMENT
  RULE__WITH_PROTRACTOR
  BATTERY__ZINC_COPPER
  EQUATORIUM
  GUN
  SLIDE_RULE
  MAGNETOMETER__KEW_PATTERN
  GALVANOMETER__DRYSDALE_TINSLEY
  CALORIMETER__DARLING_FUEL
  MERCURY_SHOWER_TUBE
  ESCAPEMENT__DEAD_BEAT
  GALVANOMETER__AYRTON_MATHER
  SURVEYING_INSTRUMENT
  SPHEROGRAPH
  HYGROMETER
  GRAPHOMETER
  CALLIPERS
  INDUCTION_COIL__WEINHOLD
  GUNSIGHT
  MODEL__ANGLED_COG_WHEELS
  MODEL__CRYSTAL
  MIRROR__SPECULUM
  ALIDADE
  MODEL__PHYSICS
  ENGINE__STEAM__HERO_S_AEOLIPILE
  THERMOMETER__MERCURY
  SECOHMMETER
  RHEOSTAT__WHEATSTONE
  HYGROMETER__ABSORPTION__COVENTRY
  ARTIFICIAL_HORIZON
  CHAIN
  CHRONOMETER__SOLAR
  ELECTROSTATIC_GENERATOR__WHEATSTONE
  MOONDIAL
  SPEAKING_TRUMPET
  PLUMB_BOB
  WATTMETER
  AZIMUTH_CIRCLE
  THERMOELECTROMETER
  MAGNETOMETER__VIBRATION
  SUNDIAL
  TAPE_MEASURE__SPRING
  GONIOMETER
  GALVANOMETER__VIBRATION
  SECTOGRAPH
  GAUGE_PART
  BINOCULARS__PRISM
  CHEMICAL
  MEDICAL_GALVANIC_INSTRUMENT
  MEASURING_BAR
  SECTOR
  TIDE_CALCULATOR
  DEPTH_FINDER
  CINEMATOGRAPH_SPOOL_WINDER
  POTENTIOMETER__VERNIER
  DISCHARGE_TUBE__CROOKES
  TELEPHONE
  FLASK__GAS_CONTAINER
  GALVANOMETER__DUDDELL_OSCILLOGRAPH
  PITCHOMETER
  BAROMETER_REGISTER_PLATE
  ELECTRICAL_MACHINE__GRAMME
  VIBRATION_APPARATUS
  ELECTROSTATIC_GENERATOR__CUTHBERTSON
  QUADRANT__ARTILLERY
  HYDROSTATICS
  PROTRACTOR__ON_RULE
  THERMOMETER__MALT_KILN
  WATER_BATH
  HOURGLASS
  CONDENSER__VARIABLE
  CAMERA_EQUIPMENT
  FOUCAULT_PENDULUM
  GAUGE__GAS
  KALEIDOSCOPE
  MAGNETIC_NEEDLE
  MIRROR__CONCAVE
  PHYSIOLOGICAL_INSTRUMENT
  STORM_GLASS
  ELECTRIC_TIME_DISTRIBUTION_SYSTEM
  COMPASS__ELLIPTICAL
  SURVEYOR_S_TAPE
  PHOTOMETER__WHEATSTONE
  PEN__ELECTRICAL_RECORDING
  OPTICAL_STAND
  AERATING_FLUID
  DEMONSTRATION_APPARATUS
  PLANIMETER__AMSLER
  LENS__TELESCOPE_OBJECTIVE
  PRISM__FRESNEL
  THERMOMETER__MINIMUM
  QUADRANT__ASTROLABE
  SUNDIAL__HORIZONTAL_DIAL
  POLISHING_TOOL
  LENS__MICROSCOPE
  QUADRANT__DAVIS
  BALANCE__ROCKER_COIN
  SPECTROHELIOGRAPH
  VOLVELLE
  PRISM__HOUSED
  NOCTURNAL
  TAILOR_S_SQUARE__FOLDING
  SPINTHARISCOPE
  CAMERA_LUCIDA_PART
  BLOWPIPE
  GENERATOR__FRICTIONAL__HYDRO_ELECTRIC
  TRAMMEL__ELLIPTICAL
  GALVANOMETER__CAMPBELL_VIBRATION
  MELDOMETER
  SURVEYOR_S_STAFF
  WEIGHTS__STANDARD__IMPERIAL
  AUDIO_EQUIPMENT
  INDICATOR
  LOGARITHMIC_SCALE
  PHOTOGRAPHIC_PAPER
  THERMAL_INSTRUMENT
  CIPHER_DIAL
  SWITCHBOARD
  DISCHARGE_TUBE__THOMSON
  ENGINE__ELECTROMAGNETIC
  BATTERY__BICHROMATE
  SEXTANT__PILLAR_FRAME
  TELESCOPE__GRAPHIC
  ADMIRALTY_CHART
  BAROMETER__ANGLE
  MAGNET__ROTATING
  STIGMOGRAPH
  SPANGLED_GLOBE
  STANDARD_LENGTH
  BAROGRAPH__ANEROID
  DISCHARGE_TUBE__LENARD
  CALENDAR
  TELESCOPE_MIRROR
  TUNING_FORK__ELECTROMAGNETIC
  CRUCIBLE__PIERCED_BASE
  PULLEY_FRAME
  ENGINE__COMPOUND
  COMPASS__MINER_S
  SOUNDING_MACHINE
  LUNARIUM
  TIME_BALL
  WIMSHURST_MACHINE
  ANEMOMETER__ROBINSON_BECKLEY_RECORDING
  RULE__FOLDING
  CABLE__ELECTRIC
  BAROMETER__PORTABLE_ANEROID
  SPYGLASS
  THERMOMETER__ELBOW_RIGHT_ANGLE
  LENS__PLANO_CONVEX
  PARALLEL_PLATES
  BALANCE__MEDICAL
  VOLTMETER__RECORDING
  CALCULATOR__MECHANICAL
  CLINOMETER__ARTILLERY
  PRINTING_EQUIPMENT
  SECTOR__ASTRONOMICAL
  EIDOGRAPH
  TELESCOPE_ACCESSORY
  PHOTOGRAPHIC_DRY_PLATE
  NAVIGATION_TABLE
  SHORT_WAVE_RADIO
  WATER_LEVEL_RECORDER
  VOLTMETER
  STANDARD_VOLUME
  DELEZENNE_CIRCLE
  MIRROR__OPTICAL
  CAMERA__BINOCULAR
  CATHETOMETER
  ELECTROMETER__QUADRANT__KELVIN
  WEIGHTS__COIN
  HYDROMETER__SIKES
  ALCOHOLOMETER
  COMMUNICATIONS_EQUIPMENT
  LAMP__OIL
  CALORIMETER
  MODEL__TRIANGULAR_CRANK
  BAROMETER__POCKET
  TELESCOPE__WALKING_STICK
  CALCULATING_DEVICE
  CALENDAR__PERPETUAL
  DISCHARGE_TUBE__AURORA
  BALANCE__MAGNETIC
  CITROMETER
  ODONTOGRAPH
  GAUGE__PRESSURE
  NAVIGATIONAL_DIVIDERS
  MIRROR__CONCAVE_AND_CONVEX
  GUNTER_S_CHAIN
  MICROMETER
  SPECTROSCOPE__PHOTOGRAPHIC__LITTROW
  CROSS_STAFF_HEAD__FRENCH_FORM
  MICROMETER__PIVOT
  SURVEYOR_S_CHAIN
  BRIDGE
  QUADRANT__MURAL
  INTERFEROMETER
  LODESTONE
  CRYOPHORUS
  CAMERA_LUCIDA_EYEPIECE
  FOUNTAIN
  ELECTROMETER__LINDEMANN
  FLASK__SWAN_NECK
  HYDROMETER__TWADDELL
  THERMOMETER__MAXIMUM
  GLOBE__TERRESTRIAL
  LEVEL__SURVEYOR_S
  COMPASS__GEOMANTIC
  HYDROMETER__NICHOLSON_S
  POLARISCOPE
  CALCULATING_MACHINE
  SEXTANT__BOX
  MINER_S_DIAL
  CHART__ASTRONOMICAL
  MODEL__CROSS_CAM
  CORONAGRAPH
  GAUGE__RAIN__BECKLEY_SELF_RECORDING_
  MICROSCOPE__SIMPLE__COMPASS
  HYDROSCOPE
  PLANE_TABLE
  ELECTROMAGNETIC_APPARATUS
  MINING_INSTRUMENT
  GLOBE__TABLE
  TELESCOPE__LORD_BURY
  LENS__CONVEX
  PROSPECT_GLASS
  BINOCULARS
  LENS__PHOTOGRAPHIC
  ELECTRICAL_INSTRUMENT
  MANOMETRIC_FLAME_APPARATUS__ANALYSER
  TRANSFORMER
  ELECTROMETER__BRAUN
  STADIMETER
  MODEL__PISTON_ENGINE
  OPTICAL_BENCH
  THUNDERGLASS
  CHART_RECORDER
  SLIDE_RULE__FULLER_CYLINDRICAL
  HYGROMETER__HAIR
  MICROSCOPE_OBJECTIVE
  BALANCE__EQUAL_ARM
  TEST_TUBE
  MICROSCOPE_WHEELS_OF_APERTURES
  THERMO_HYDROMETER
  ZENITH_INSTRUMENT
  MICROSCOPE__SCREW_BARREL
  BALANCE__ELECTRIC
  ENGINEERING_INSTRUMENT
  HYDROMETER__BATTERY_TESTING
  ALMUCANTAR_STAFF
  ENGINE__PNEUMATIC
  PROJECTOR
  CLOCK_PART
  HYDROSTATIC_INSTRUMENT
  LIGHT_INTERFERENCE_SLIT
  BURNER__OXY_HYDROGEN
  BAROMETER__DIAGONAL
  GAUGE__CALLIPER
  SPEAR_FOR_MICROSCOPE_SPECIMEN
  BURNER__GAS
  ASTROLABE
  LENS__CONCAVE
  MILLIVOLT_METER
  WEATHER_PROGNOSTICATOR
  SOLENOID
  COMPASS_CARD
  LENS__SPECTACLES
  SPECTROSCOPE__DIRECT_VISION
  VOLT_RATIO_BOX
  POLARISCOPE__NORREMBERG
  BALANCE
  DRAWING_INSTRUMENT
  TELESCOPE
  THERMOGRAPH
  PHOTOGRAPHIC_INSTRUMENT
  PRESSURE_RECORDER
  LABORATORY_EQUIPMENT
  MODEL__THERMODYNAMIC_SURFACE
  PHOSPHOROSCOPE__BECQUEREL
  SHIP_S_LOG
  SCIENTIFIC_APPARATUS
  SYPHON
  ENGINEER_S_SCALE
  TELESCOPE__GREGORIAN
  GAUGING_ROD
  HYDROMETER_PART
  POGGENDORF_BRIDGE
  POSITION_INDICATOR
  TIMER
  CHRONOGRAPH
  MODEL__CHEMISTRY
  ELECTROMETER__QUADRANT
  MASSEY_S_LOG
  PHOTOGRAPHY_EQUIPMENT__COLLODIO_TYPE
  STATION_POINTER
  ELECTRONIC_CHART
  COMPASS__MAGNETIC
  MAGNETIC_CURATIVE_APPLIANCE
  PHOTOGRAPHIC_VIEWING_EQUIPMENT
  NAPIER_S_BONES
  STAND_WITH_GLASS_U_TUBES
  SUNDIAL__PORTABLE
  EYEWEAR
  REACTION_VESSEL
  MACHINE
  QUADRANT__GUNTER
  PULLEY_WHEEL
  BINNACLE
  COMPASS__MAGNETIC_PRISMATIC
  GUNNERY_SCALE
  GUNTER_S_SCALE
  LAMP__CANDLE
  ECLIPSE_GLASSES
  SUNDIAL__UNIVERSAL_RING_DIAL
  TELESCOPE__MARINE
  LAMP
  COMPASS__POCKET
  PRISM_STAND
  COMPASS__DRAFTING
  SLIDE_RULE__HANNYNGTON
  CLOCK__WHEATSTONE
  BALANCE__ELECTROMAGNETIC
  PART
  PHOSPHOROSCOPE
  POTENTIOMETER
  PERSPECTIVE_MACHINE
  MODEL__LINEAR_COGS
  CARBON_ARC_LAMP
  HYDROMETER__ASHTON
  LENS__ACHROMATIC
  MICROSCOPE__GOULD
  NAVIGATIONAL_PLOTTER
  THUNDER_HOUSE
  BAROMETER__DEMONSTRATION_BANJO
  WEIGHTS__STANDARD__METRIC
  THERMOMETER__DEEP_SEA
  PRINTING_FRAME
  CHAIN_SCALES
  PROJECTION_LANTERN
  BATTERY__ZINC_CARBON
  PHENAKISTOSCOPE
  ERGOGRAPH
  THERMOMETER__DIAL
  GALVANOMETER__TANGENT__STEWART
  AZIMUTH_INSTRUMENT
  GAUGE__SHOT
  GAUGE__STEAM
  GALVANOMETER__ASTATIC__NOBILI
  MODEL__ANATOMICAL
  CHONDROMETER
  THERMO_SACCHAROMETER
  GLOBE
  ELECTRODYNAMOMETER
  INDUCTION_COIL
  EYEPIECE
  PARALLEL_RULE__ROLLING
  BALANCE__COMPENSATION
  GAUGING_RULE
  HELIOGRAPH
  STEREOSCOPE__WHEATSTONE
  ELECTROSTATIC_GENERATOR__NAIRNE
  PRISM__CYANIN
  BALANCE__COIN
  LEVEL__WATER
  RADIOGRAPHIC_APPARATUS
  PHOTOHELIOGRAPH
  PHOTOMETER__LUMMER_BRODHUN
  GALVANOMETER__BROCA
  SUNDIAL__RING_DIAL
  MODEL__LIGHTNING_CONDUCTOR
  RESISTANCE_COIL
  MORTAR_AND_PESTLE
  CAMERA_OBSCURA
  COMPASS__AIR
  DIPSTICK
  COUNTER
  BOTTLE
  HAND_LENS
  HYDROMETER__TAR_TESTER
  ELECTROSTATIC_APPARATUS
  DIAGRAM
  TELEGRAPH_POLE
  SONOMETER__HUBBARD_MONOCHORD
  GRINDING_TOOL
  MIRROR__ANGLED
  BAROMETER__BANJO
  KEY
  DAGUERREOTYPE_APPARATUS
  PARALLEL_RULE
  BALANCE__FOLDING_COIN
  BINNACLE__MAGNETIC
  MICROSCOPE__CUFF
  ANEMOMETER__ROBINSON
  SOUNDING_BOWL
  ELECTROMAGNETIC_ROTATION_APPARATUS
  BALANCE__BERANGER
  FLASK__HEMPEL
  ELECTROMETER__TORSION__COULOMB
  QUADRANT__ASTROLABE__DOUBLE
  LEYDEN_JAR_BATTERY
  MODEL__LENS
  AIR_PUMP
  BAROGRAPH__PHOTOGRAPHIC
  BELL
  MEASURE__MILK
  LEVELLING_STAVE
  RELAY
  MAGNETOMETER__EWLES__DAMPING
  COMPASS_PART
  MEDICAL_CURATIVE_APPLIANCE
  MARINE_SANDGLASS
  PULLEY_PART
  KINETOSCOPE
  MICROSCOPE__JONES
  ARCHITECT_S_SCALE
  GAUGE__RAIN__RECORDING_
  OSCILLOGRAPH
  GRAPHOSCOPE
  PELORUS
  CLOCK__WATER_DRIVEN__FREE__PENDULUM
  INCLINED_PLANE
  MODEL__PADDLEWHEEL
  SUNDIAL__UNIVERSAL_DIAL
  SYRINGE
  BALANCE__KEATES
  ORGAN_PIPE_PART
  SCIENTIFIC_NOVELTY
  MODEL__TURBINE
  PYROMETER__WEDGWOOD
  INSULATOR
  SCALE
  THERMOPILE
  SPECTACLES
  ALCOHOLOMETER__FIELD_S
  CAMERA__MICROPHOTOGRAPHY
  GAUGE__JEWEL_HOLE
  INDUCTION_COIL__RUHMKORFF
  ELECTRICAL_EQUIPMENT
  WAVE_DEMONSTRATION_APPARATUS
  TELESCOPE_MOUNT
  MONOCULAR
  DIFFRACTION_GRATING
  WHISTLE__LOCOMOTIVE
  ELECTROTHERAPY_DEVICE
  COMPENDIUM__ASTRONOMICAL
  SPHEROMETER
  WATER_METER
  LENGTH_MEASURING_DEVICE
  THERMOMETER__DESK
  GALTON_WHISTLE
  MEASURING_CYLINDER__GAS
  MODEL__EAR
  RULE__ULLAGE
  BAROMETER__WHEEL
  STANDARD_CELL__ZINC_MERCURY
  STAND__CONDENSER
  MEASURE
  STEREOMICROSCOPE
  MODEL__DROP_VALVE_ENGINE
  HELIOSTAT__STONEY
  LENTHALL_COURSE_DELINEATOR
  DIAGRAM__ASTRONOMICAL
  PHOTOGRAPH
  MANOMETER__FICK_SPRING
  TELEGRAPH
  RETORT
  CLAMP__SEXTANT
  DIFFRACTION_APPARATUS
  STEAM_HEATER
  FUNNEL
  BALANCE__CHEMICAL
  MEDICAL_INSTRUMENT
  THERMOMETER__MINING
  BAROMETER__MARINER_S__RECORDING
  PHOTOGRAPHY_EQUIPMENT__CALOTYPE
  CINEMATOGRAPH
  SPEEDOMETER__MOTOR_CAR
  STAND__ADJUSTABLE
  VOLTMETER__ELECTROSTATIC
  DOME__ASTRONOMICAL
  STANDARD_YARD
  ELECTRIC_MOTOR
  ELECTROCHEMICAL_CELL
  LIGHT_DEFRACTOR
  BATTERY__MAYNOOTH
  LENS__PLANO_CONCAVE
  COMPENDIUM__OPTICAL
  GONIOMETER__REFRACTION
  HYDROMETER__DIABETES
  PLANE_TABLE_FRAME
  HYGROMETER__MASON
  MODEL__VERTICAL_ROD_DRIVE
  MAGNET__HORSESHOE
  HYGROMETER__WHALE_BONE
  COMPASS__DRY_CARD
  AIR_GUN
  COMPUTING_SCALE
  MODEL__ASTRONOMICAL
  STANDARD_VOLUME__IMPERIAL
  THERMOMETER__LESLIE_DIFFERENTIAL
  ANEMOMETER
  HYPSOMETER
  MODEL__WATER_WHEEL
  MODEL__COMPUTING_MACHINE
  PENDULUM__MERCURY_COMPENSATED
  THERMOMETER__MAXIMUM_AND_MINIMUM
  THERMOMETER__RECORDING
  MICROMETER_SCREW_GAUGE
  DENDROMETER
  SLIDE_RULE__CATHOLIC_ORGANON
  PERISCOPE
  ELECTROMETER__WEIGHT
  PHOTOGRAPHIC_CHANGING_BOX
  MODEL
  ANEMOMETER__DINES__RECORDING
  CALLIPERS__GUNNER_S
  MODEL__ROTATION_DIRECTION
  HYDRAULIC_MACHINERY
  SOUNDING_TUBE
  LENS__FACETED
  GALVANOMETER__BALLISTIC_MIRROR
  MODEL__EYE
  ELECTRICAL_MACHINE__GALVANO
  HORSE_MEASURE
  PLANE_TABLE_PART
  COMPASS__PLANE_TABLE
  CINEMATOGRAPH_EQUIPMENT
  LEVEL__SPIRIT
  STANDARD_VOLUME__METRIC
  MIRROR__AZIMUTH
  MECHANICAL_STAGE
  MIRROR__CONVEX
  ELECTROMETER_PLATES_VOLTAGE_ADJUSTER
  MICROSCOPE__CULPEPER
  PLANISPHERE__UNIVERSAL
  CALORIMETER__THOMPSON_FUEL
  WINGED_DIVIDERS
  MORSE_KEY
  ELECTRIC_DISCHARGE_DEMONSTRATION_APPARATUS
  GAUGE__PAPER
  OPISOMETER
  SURVEYING_EQUIPMENT
  HELIOSTAT
  WEIGHTS__STANDARD
  RECTIFIER
  SEXTANT__LUNAR
  SPECTACLE_FRAMES
  ELECTRIC_PISTOL
  PERISCOPE__FIELD
  TELECOMMUNICATIONS_EQUIPMENT
  CONDENSER
  FLASK__PRECIPITATING_AND_OTHER_CYLINDER
  PERPETUAL_MOTION_MACHINE
  SUNDIAL__EQUINOCTIAL_DIAL
  TELESCOPE__PERSPECTIVE_GLASS
  WIND_GUN
  ORGAN__DEMONSTRATION
  CARPENTER_S_SQUARE
  MAGNETIC_APPARATUS
  MIRROR__DIAGONAL
  CHLADNI_PLATE_ACCESSORY
  ELECTROMETER__HENLEY
  NEEDLE
  CROSS_STAFF
  WATER_JACKET
  DRAFTING_SET
  WEATHER_INDICATOR
  BALANCE__MATHEMATICAL
  GYROSCOPE
  GONIOMETER__CRYSTAL__WOLLASTON
  COLORIMETER
  MODEL__PUNCH
  CAMERA__NOVELTY
  MICROSCOPE__SIMPLE
  SIREN__SEEBECK
  BAROMETER__MAGALAENS
  DR_FOX_S_SHADOW_METER
  ELECTROPHORUS
  OPTICAL_INSTRUMENT
  LEVEL__GUNNER_S
  BALANCE__LETTER
  EQUATORIAL_INSTRUMENT
  MICROSPECTROSCOPE
  OPTICAL_SQUARE
  MAGNET__ARTIFICIAL
  LEVEL__HAND
  PERSPECTIVE_GLASS
  HYDRAULIC_SCREW
  SALINOMETER
  CONDENSER__STANDARD
  COMPASS__PRISMATIC
  LIGHT_BOX
  CAVALRY_SKETCHING_BOARD
  THERMOSCOPE
  CAMERA__PORTABLE
  DIAGRAM__MAGNETIC
  GAUGE__CATTLE
  LENTHALL_TIDE_INDICATOR
  COMPASS_ADJUSTER
  STANDARD_INCH
  MICROSCOPE_STAGE
  ENGINE__CONDENSING
  LEVEL
  CLOCK_ESCAPEMENT
  PRISM
  GALVANOMETER__TANGENT__GAUGAIN
  MEASURING_LINE
  TELEGRAPHIC_APPARATUS
  READING_GLASSES
  CRYOPHORUS__WOLLASTON
  TUNING_FORK__LISSAJOUS
  GLOBE__FOLDING
  BURNER__ACETYLENE
  MODEL__THREE_WAY_MOTION
  MAP
  OHMMETER
  DEVIATOMETER
  PRISM__JELLETT
  WEIGHING_MACHINE__PERSON
  CENTRIFUGE
  FORCE_PUMP
  WATCH__ALARM
  LEVEL__MARINE
  GALVANOMETER__CURRENT
  MODEL__ELECTRIC_MOTOR
  TELESCOPIC_SIGHTS
  LENS_BOARD
  ANEMOMETER__BIRAM_S
  STANDARD_CELL__WESTON
  GLOBE__INFLATABLE
  MICROSCOPE_LAMP
  MICROSCOPE__COMPOUND__MUSEUM
  CIRCULAR_CALCULATOR
  MAGNETOMETER
  PRISM_TRAIN
  VOLTMETER__MULTICELLULAR
  ELECTROSTATIC_CHAMBER
  FUNNEL__RETORT_FILLING
  CALCULATOR__LUNAR_AND_TIDAL
  BAROMETER__COASTAL
  GUN_PART
  SACCHAROMETER
  MAGIC_LANTERN
  ACTINOMETER
  PRISM__HOLLOW
  ELECTROMAGNETIC_INDUCTION_MACHINE
  FLASK__DEWAR
  DIVIDERS
  DENTAL_INSTRUMENT
  TRAMMEL
  FLASK__MEASURING
  SPRING
  ABACUS
  COMPASS__RECORDING
  LONGITUDE_INSTRUMENT
  MODEL__MOON_SURFACE
  BALANCE__YARN
  AIR_FOUNTAIN
  ELECTROSTATIC_ROD
  MEASURING_TAPE__SURVEYOR_S
  WHEATSTONE_BRIDGE
  LOG_GLASS
  SHIP_S_LOG__ELECTRIC
  STEAM_ENGINE_INDICATOR
  TUNING_FORK
  MODEL__BEAM_ENGINE
  BURETTE
  OSCILLOGRAPH__IRWIN_PAUL
  OSCILLATION_TRANSFORMER
  MICROSCOPE__SOLAR
  CENTRIFUGE__GERBER
  BAROMETER__FITZROY
  PHILOSOPHICAL_TABLE
  BALANCE__GOLD
  GUNTER_S_SCALE__SLIDING
  MICROSCOPE
  DIVIDED_CIRCLE
  MAGIC_LANTERN__THE_METAMORPHOSER
  SIREN__HELMHOLTZ_DOUBLE
  MICROSCOPE_SCREW
  MODEL__DRILL
  GUNNER_S_MOUTHPIECE
  CONCHOIDOGRAPH
  SUNDIAL__MULTIPLE_DIAL
  HOT_HOUSE
  PICTURE
  BARREL
  SILVERWARE
  ROLLER_BLIND
  STOVE
  DIAGRAM__MAGIC
  TORPEDO
  CURTAIN_ROD
  HANDLE
  WARMING_PAN
  PAINT
  HOT_BATH
  ORNAMENT
  MACHINE__WASHING
  MACHINE__SEWING
  WHIP_MOUNT
  SHIP_COLOUR
  MACHINERY__AGRICULTURAL
  LETTER
  MACHINE__CARPET
  SHOE__THREAD
  CANISTER__TEA
  TEA
  COACH_HARNESS
  INK
  FISHING_REEL
  NAIL
  RAW_MATERIAL
  MATTRESS
  PINCER
  CANDLE_SNUFFER
  HARDWARE
  WINE
  SPIRITS
  MAST
  MAP_ROLLER
  HANDLE__SAW
  HANDKERCHIEF
  ANCHOR
  SHOP_FITTING
  DRAWING
  TUBE
  LOOKING_GLASS
  DIE_STOCK
  GLASS__PLATE
  FRAME
  PAPER_TRAY
  STOVE__COOKING
  MUSICAL_BOX
  CARPET
  HOSE
  CANISTER
  SHIP_S_LAMP
  BOOK
  PRINT_MUSIC
  BUTTON
  INKSTAND
  COMB
  ENVELOPE_MAKING_MACHINE
  PRINT
  HARPSICHORD
  POWDER_FLASK
  BEDSTEAD
  CUTLERY
  FIRE_ENGINE
  CANE
  BOOKCASE
  CUTLERY_HANDLE
  WIRE
  HAMMER
  FLAG
  PLATE
  SCREWPLATE
  FANLIGHT
  PIANO_FORTE
  CURIOSITY
  DOLL
  MACHINE__TEXTILE
  CABINET
  CASE__JEWEL
  MACHINE__CHIMNEY_SWEEPING
  PRESS__SCREW
  SEAL
  FINE_ART
  PAPER_CASE
  LATHE
  STORE
  CARRIAGE
  TEXTILE
  BREWING_APPLIANCE
  BRUSH__HEARTH
  BILLIARD_TABLE
  COFFEE
  BEER_MACHINE
  KNIFE__HAFT
  NOTEPAD
  DOG_COLLAR
  COLOUR
  MOTION
  SHOE__LATCHET
  MACHINE__MEDAL_ENGRAVING
  ARTIFICIAL_FEATHER
  COFFIN_FURNITURE
  SAW
  SACK__COAL
  RING
  JEWELLERY
  CRICKET_BAT
  SAUSAGE__ITALIAN
  MACHINE__MONEY
  THEATRICAL_ORNAMENT
  BELT__SHOT
  STOVE__GAS
  CORKSCREW
  FISHING_TACKLE
  SHOVEL
  STOCK_AND_DIE
  CASE__DRESSING
  CANDLE
  VICE
  BRACE_AND_BIT
  BONE_MOULD
  BOOK_PLATE
  ORGAN
  BULLION
  CANDLESTICK
  ROLL
  BED_SCREW
  SAIL
  SPERMACETTI_CANDLE
  UMBRELLA
  STONEWARE
  MILL
  SODA_WATER
  CHIMES__CHURCH
  RAG
  CASE__LOCK
  LOCK
  BRACE
  COIN
  ARTIFICIAL_FLOWER
  MACHINE__FLOUR
  TRUSS
  MUSIC
  SHOE
  FILTERING_STONE
  PHOTOGRAPH_ALBUM
  LACE
  TEA_URN
  CONSUMABLE
}

enum RoleTypes {
  MASTER
  MASTER_OF_LIVERY_COMPANY
  ASSISTANT
  MASTER_OF_GUILD
  WARDEN
  PRIME_WARDEN
  JOURNEYMAN
  CROWN_AGENT
}

enum EducatorRoleTypes {
  LECTURER
  PROFESSOR
  TEACHER
  EXAMINER
}

enum BusinessAppointmentTypes {
  OPTICIAN
  ROYAL_APPOINTMENT___HYDROGRAPHER
  ROYAL_APPOINTMENT
}

enum OrganisationType {
  LEARNED_SOCIETY
  BUSINESS
  GUILD
  RESEARCH_INSTITUTION
  UNIVERSITY
  SCHOOL
  GOVERNMENT_BODY
  OVERSEAS_TRADING_COMPANY
  TRAINING_INSTITUTION
}

enum DateType {
  OCCURRED_BEFORE
  KNOWN_DATE
  OCCURRED_AFTER
}

enum AddressFunction {
  RESIDENCE
  ADDITIONAL_OUTLET
  SUBSIDIARY
  SCHOOL
  AGENCY
  FACTORY
  PRIMARY_OUTLET
  TESTING_STATION
  MULTIPLE_OCCUPANCY
}

enum Genders {
  MALE
  FEMALE
}

enum CivicRoleTypes {
  LORD_MAYOR
  COUNCILLOR
  CHURCHWARDEN
  MAYOR
  ALDERMAN
  LORD_PROVOST
  BURGESS
  SHERIFF
}

enum SentenceType {
  UNDEFINED
}

"""
unions
"""
union OrganisationOrPerson = Organisation | Person

union ObjectOrSource = Object | Source

union AddressOrPlace = Address | Place

union ExhibitionOrOrganisationOrPerson = Exhibition | Organisation | Person

"""
models
"""
type Takeover {
  TookOver: Organisation! @relationship(type: "TookOver", direction: OUT)
  TakenOverBy: OrganisationOrPerson!
    @relationship(type: "TakenOverBy", direction: OUT)
  TakeoverDateConfidenceType: ConfidenceType
  TakeoverDateConfidenceNote: String
  TakeoverDateConfidenceProbabilityValue: Float
  TakeoverDateConfidenceAssessmentAdditionalNotes: String
  TakeoverDateAdditionalNotes: String
  TakeoverDateValue: DateValue
  TakeoverDateType: DateType
  TakeoverAdditionalNotes: String
}

type Survey {
  SurveyEndDateConfidenceType: ConfidenceType
  SurveyEndDateConfidenceNote: String
  SurveyEndDateConfidenceProbabilityValue: Float
  SurveyEndDateConfidenceAssessmentAdditionalNotes: String
  SurveyEndDateAdditionalNotes: String
  SurveyEndDateValue: DateValue
  SurveyEndDateType: DateType
  PlacesSurveyed: [Place!]!
    @relationship(type: "PlacesSurveyed", direction: OUT)
  SurveyCarriedOutBy: [OrganisationOrPerson!]!
    @relationship(type: "SurveyCarriedOutBy", direction: OUT)
  SurveyAdditionalNotes: String
  SurveyName: String
  SurveyStartDateConfidenceType: ConfidenceType
  SurveyStartDateConfidenceNote: String
  SurveyStartDateConfidenceProbabilityValue: Float
  SurveyStartDateConfidenceAssessmentAdditionalNotes: String
  SurveyStartDateAdditionalNotes: String
  SurveyStartDateValue: DateValue
  SurveyStartDateType: DateType
}

type Supplying {
  SupplyingStartDateConfidenceType: ConfidenceType
  SupplyingStartDateConfidenceNote: String
  SupplyingStartDateConfidenceProbabilityValue: Float
  SupplyingStartDateConfidenceAssessmentAdditionalNotes: String
  SupplyingStartDateAdditionalNotes: String
  SupplyingStartDateValue: DateValue
  SupplyingStartDateType: DateType
  SupplyingEndDateConfidenceType: ConfidenceType
  SupplyingEndDateConfidenceNote: String
  SupplyingEndDateConfidenceProbabilityValue: Float
  SupplyingEndDateConfidenceAssessmentAdditionalNotes: String
  SupplyingEndDateAdditionalNotes: String
  SupplyingEndDateValue: DateValue
  SupplyingEndDateType: DateType
  SuppliedBy: OrganisationOrPerson!
    @relationship(type: "SuppliedBy", direction: OUT)
  SuppliedTo: OrganisationOrPerson!
    @relationship(type: "SuppliedTo", direction: OUT)
  SuppliedObjectsofType: [ObjectTypes!]
  SuppliedSpecificObjects: [Object!]!
    @relationship(type: "SuppliedSpecificObjects", direction: OUT)
  SuppliedObjectsProducedBy: OrganisationOrPerson!
    @relationship(type: "SuppliedObjectsProducedBy", direction: OUT)
}

type Source {
  Title: String
  ResearchNote: String
  CreationDateConfidenceType: ConfidenceType
  CreationDateConfidenceNote: String
  CreationDateConfidenceProbabilityValue: Float
  CreationDateConfidenceAssessmentAdditionalNotes: String
  CreationDateAdditionalNotes: String
  CreationDateValue: DateValue
  CreationDateType: DateType
  PublicationEndDateConfidenceType: ConfidenceType
  PublicationEndDateConfidenceNote: String
  PublicationEndDateConfidenceProbabilityValue: Float
  PublicationEndDateConfidenceAssessmentAdditionalNotes: String
  PublicationEndDateAdditionalNotes: String
  PublicationEndDateValue: DateValue
  PublicationEndDateType: DateType
  PublicationSingleDateConfidenceType: ConfidenceType
  PublicationSingleDateConfidenceNote: String
  PublicationSingleDateConfidenceProbabilityValue: Float
  PublicationSingleDateConfidenceAssessmentAdditionalNotes: String
  PublicationSingleDateAdditionalNotes: String
  PublicationSingleDateValue: DateValue
  PublicationSingleDateType: DateType
  PlaceofPublication: Place!
    @relationship(type: "PlaceofPublication", direction: OUT)
  HeldBy: OrganisationOrPerson! @relationship(type: "HeldBy", direction: OUT)
  CatalogueRecordURL: String
  HasCatalogueIdentifier: String
  SourceType: SourceTypes
  MSSReference: String
  Creator: [OrganisationOrPerson!]!
    @relationship(type: "Creator", direction: OUT)
  PageRange: String
  HasPart: ObjectOrSource! @relationship(type: "HasPart", direction: OUT)
  Publisher: OrganisationOrPerson!
    @relationship(type: "Publisher", direction: OUT)
  Editor: [OrganisationOrPerson!]! @relationship(type: "Editor", direction: OUT)
  Addressee: [OrganisationOrPerson!]!
    @relationship(type: "Addressee", direction: OUT)
  Translator: [OrganisationOrPerson!]!
    @relationship(type: "Translator", direction: OUT)
  Citation: String
  PublicationStartDateConfidenceType: ConfidenceType
  PublicationStartDateConfidenceNote: String
  PublicationStartDateConfidenceProbabilityValue: Float
  PublicationStartDateConfidenceAssessmentAdditionalNotes: String
  PublicationStartDateAdditionalNotes: String
  PublicationStartDateValue: DateValue
  PublicationStartDateType: DateType
  AbbreviatedCitation: String
}

type RoyalAppointment {
  RoyalAppointmentEndDateConfidenceType: ConfidenceType
  RoyalAppointmentEndDateConfidenceNote: String
  RoyalAppointmentEndDateConfidenceProbabilityValue: Float
  RoyalAppointmentEndDateConfidenceAssessmentAdditionalNotes: String
  RoyalAppointmentEndDateAdditionalNotes: String
  RoyalAppointmentEndDateValue: DateValue
  RoyalAppointmentEndDateType: DateType
  RoyalAppointmentAdditionalNotes: String
  RoyalAppointmentMakerAppointed: OrganisationOrPerson!
    @relationship(type: "RoyalAppointmentMakerAppointed", direction: OUT)
  RoyalAppointmentMadeBy: OrganisationOrPerson!
    @relationship(type: "RoyalAppointmentMadeBy", direction: OUT)
  RoyalAppointmentStartDateConfidenceType: ConfidenceType
  RoyalAppointmentStartDateConfidenceNote: String
  RoyalAppointmentStartDateConfidenceProbabilityValue: Float
  RoyalAppointmentStartDateConfidenceAssessmentAdditionalNotes: String
  RoyalAppointmentStartDateAdditionalNotes: String
  RoyalAppointmentStartDateValue: DateValue
  RoyalAppointmentStartDateType: DateType
}

type Producing {
  ProducedSpecificObjects: [Object!]!
    @relationship(type: "ProducedSpecificObjects", direction: OUT)
  ProducedObjectsBy: [OrganisationOrPerson!]!
    @relationship(type: "ProducedObjectsBy", direction: OUT)
  ProducedObjectsFor: [OrganisationOrPerson!]!
    @relationship(type: "ProducedObjectsFor", direction: OUT)
  Producer: [OrganisationOrPerson!]!
    @relationship(type: "Producer", direction: OUT)
  ProductionStartDateConfidenceType: ConfidenceType
  ProductionStartDateConfidenceNote: String
  ProductionStartDateConfidenceProbabilityValue: Float
  ProductionStartDateConfidenceAssessmentAdditionalNotes: String
  ProductionStartDateAdditionalNotes: String
  ProductionStartDateValue: DateValue
  ProductionStartDateType: DateType
  ProductionEndDateConfidenceType: ConfidenceType
  ProductionEndDateConfidenceNote: String
  ProductionEndDateConfidenceProbabilityValue: Float
  ProductionEndDateConfidenceAssessmentAdditionalNotes: String
  ProductionEndDateAdditionalNotes: String
  ProductionEndDateValue: DateValue
  ProductionEndDateType: DateType
  ProducedObjectsofTypes: [ObjectTypes!]
}

type Place {
  PlaceName: String
  PlaceGeonamesIdentifier: String
  PlaceGettyIdentifier: String
  Location: String
  PlaceDocumentedInSource: [Source!]!
    @relationship(type: "PlaceDocumentedInSource", direction: OUT)
  PlaceAdditionalNotes: String
}

type Person {
  FlourishingStartDateAdditionalNotes: String
  FlourishingStartDateType: DateType
  FlourishingEndDateAdditionalNotes: String
  FlourishingEndDateValue: DateValue
  FlourishingStartDateValue: DateValue
  FlourishingStartDateConfidenceType: ConfidenceType
  FlourishingStartDateConfidenceNote: String
  FlourishingStartDateConfidenceProbabilityValue: Float
  FlourishingStartDateConfidenceAssessmentAdditionalNotes: String
  FlourishingEndDateConfidenceType: ConfidenceType
  FlourishingEndDateType: DateType
  FlourishingEndDateConfidenceNote: String
  FlourishingEndDateConfidenceProbabilityValue: Float
  FlourishingEndDateConfidenceAssessmentAdditionalNotes: String
  ResearchNote: String
  SIMONDisambiguationNumeral: String
  DeathDateConfidenceType: ConfidenceType
  DeathDateConfidenceNote: String
  DeathDateConfidenceProbabilityValue: Float
  DeathDateConfidenceAssessmentAdditionalNotes: String
  DeathDateAdditionalNotes: String
  DeathDateValue: DateValue
  DeathDateType: DateType
  FriendOf: [Person!]! @relationship(type: "FriendOf", direction: OUT)
  PlaceofBaptism: Place! @relationship(type: "PlaceofBaptism", direction: OUT)
  AssociatedPerson: [Person!]!
    @relationship(type: "AssociatedPerson", direction: OUT)
  RetirementDateConfidenceType: ConfidenceType
  RetirementDateConfidenceNote: String
  RetirementDateConfidenceProbabilityValue: Float
  RetirementDateConfidenceAssessmentAdditionalNotes: String
  RetirementDateAdditionalNotes: String
  RetirementDateValue: DateValue
  RetirementDateType: DateType
  BiographicalDescription: String
  AssociatedOrganisation: [Organisation!]!
    @relationship(type: "AssociatedOrganisation", direction: OUT)
  Gender: Genders
  Childinlaw: [Person!]! @relationship(type: "Childinlaw", direction: OUT)
  NaturalisationDateConfidenceType: ConfidenceType
  NaturalisationDateConfidenceNote: String
  NaturalisationDateConfidenceProbabilityValue: Float
  NaturalisationDateConfidenceAssessmentAdditionalNotes: String
  NaturalisationDateAdditionalNotes: String
  NaturalisationDateValue: DateValue
  NaturalisationDateType: DateType
  IncarceratingInstitution: Organisation!
    @relationship(type: "IncarceratingInstitution", direction: OUT)
  Nationality: Nationalities
  SequestrationDateConfidenceType: ConfidenceType
  SequestrationDateConfidenceNote: String
  SequestrationDateConfidenceProbabilityValue: Float
  SequestrationDateConfidenceAssessmentAdditionalNotes: String
  SequestrationDateAdditionalNotes: String
  SequestrationDateValue: DateValue
  SequestrationDateType: DateType
  SeeAlso: [OrganisationOrPerson!]!
    @relationship(type: "SeeAlso", direction: OUT)
  BirthDateConfidenceType: ConfidenceType
  BirthDateConfidenceNote: String
  BirthDateConfidenceProbabilityValue: Float
  BirthDateConfidenceAssessmentAdditionalNotes: String
  BirthDateAdditionalNotes: String
  BirthDateValue: DateValue
  BirthDateType: DateType
  NieceNephew: [Person!]! @relationship(type: "NieceNephew", direction: OUT)
  NationalityAssessmentNote: String
  WorkingStartDateAdditionalNotes: String
  WorkingStartDateType: DateType
  WorkingEndDateAdditionalNotes: String
  WorkingEndDateValue: DateValue
  WorkingStartDateValue: DateValue
  WorkingStartDateConfidenceType: ConfidenceType
  WorkingStartDateConfidenceNote: String
  WorkingStartDateConfidenceProbabilityValue: Float
  WorkingStartDateConfidenceAssessmentAdditionalNotes: String
  WorkingEndDateConfidenceType: ConfidenceType
  WorkingEndDateType: DateType
  WorkingEndDateConfidenceNote: String
  WorkingEndDateConfidenceProbabilityValue: Float
  WorkingEndDateConfidenceAssessmentAdditionalNotes: String
  NaturalisedNationality: Nationalities
  Parent: [Person!]! @relationship(type: "Parent", direction: OUT)
  OccupiedWorkhouseStartDateAdditionalNotes: String
  OccupiedWorkhouseStartDateType: DateType
  OccupiedWorkhouseEndDateAdditionalNotes: String
  OccupiedWorkhouseEndDateValue: DateValue
  OccupiedWorkhouseStartDateValue: DateValue
  OccupiedWorkhouseStartDateConfidenceType: ConfidenceType
  OccupiedWorkhouseStartDateConfidenceNote: String
  OccupiedWorkhouseStartDateConfidenceProbabilityValue: Float
  OccupiedWorkhouseStartDateConfidenceAssessmentAdditionalNotes: String
  OccupiedWorkhouseEndDateConfidenceType: ConfidenceType
  OccupiedWorkhouseEndDateType: DateType
  OccupiedWorkhouseEndDateConfidenceNote: String
  OccupiedWorkhouseEndDateConfidenceProbabilityValue: Float
  OccupiedWorkhouseEndDateConfidenceAssessmentAdditionalNotes: String
  AuntUncle: [Person!]! @relationship(type: "AuntUncle", direction: OUT)
  BankruptcyDateConfidenceType: ConfidenceType
  BankruptcyDateConfidenceNote: String
  BankruptcyDateConfidenceProbabilityValue: Float
  BankruptcyDateConfidenceAssessmentAdditionalNotes: String
  BankruptcyDateAdditionalNotes: String
  BankruptcyDateValue: DateValue
  BankruptcyDateType: DateType
  Sibling: [Person!]! @relationship(type: "Sibling", direction: OUT)
  SimonID: Float
  Parentinlaw: [Person!]! @relationship(type: "Parentinlaw", direction: OUT)
  PlaceofBirth: Place! @relationship(type: "PlaceofBirth", direction: OUT)
  IncarcerationStartDateAdditionalNotes: String
  IncarcerationStartDateType: DateType
  IncarcerationEndDateAdditionalNotes: String
  IncarcerationEndDateValue: DateValue
  IncarcerationStartDateValue: DateValue
  IncarcerationStartDateConfidenceType: ConfidenceType
  IncarcerationStartDateConfidenceNote: String
  IncarcerationStartDateConfidenceProbabilityValue: Float
  IncarcerationStartDateConfidenceAssessmentAdditionalNotes: String
  IncarcerationEndDateConfidenceType: ConfidenceType
  IncarcerationEndDateType: DateType
  IncarcerationEndDateConfidenceNote: String
  IncarcerationEndDateConfidenceProbabilityValue: Float
  IncarcerationEndDateConfidenceAssessmentAdditionalNotes: String
  GivenName: String
  Surname: String
  AlternativeGivenName: String
  WorkedFor: [OrganisationOrPerson!]!
    @relationship(type: "WorkedFor", direction: OUT)
  BurialDateConfidenceType: ConfidenceType
  BurialDateConfidenceNote: String
  BurialDateConfidenceProbabilityValue: Float
  BurialDateConfidenceAssessmentAdditionalNotes: String
  BurialDateAdditionalNotes: String
  BurialDateValue: DateValue
  BurialDateType: DateType
  BaptismDateConfidenceType: ConfidenceType
  BaptismDateConfidenceNote: String
  BaptismDateConfidenceProbabilityValue: Float
  BaptismDateConfidenceAssessmentAdditionalNotes: String
  BaptismDateAdditionalNotes: String
  BaptismDateValue: DateValue
  BaptismDateType: DateType
  AlternativeSurname: String
  DocumentedIn: Source! @relationship(type: "DocumentedIn", direction: OUT)
}

type Patenting {
  PatentedObjectsofType: ObjectTypes
  AdditionalNotes: String
  PatentRecord: Source! @relationship(type: "PatentRecord", direction: OUT)
  PatentedBy: [OrganisationOrPerson!]!
    @relationship(type: "PatentedBy", direction: OUT)
  PatentDescription: String
  PatentDateConfidenceType: ConfidenceType
  PatentDateConfidenceNote: String
  PatentDateConfidenceProbabilityValue: Float
  PatentDateConfidenceAssessmentAdditionalNotes: String
  PatentDateAdditionalNotes: String
  PatentDateValue: DateValue
  PatentDateType: DateType
}

type Ownership {
  OwnershipStartDateConfidenceType: ConfidenceType
  OwnershipStartDateConfidenceNote: String
  OwnershipStartDateConfidenceProbabilityValue: Float
  OwnershipStartDateConfidenceAssessmentAdditionalNotes: String
  OwnershipStartDateAdditionalNotes: String
  OwnershipStartDateValue: DateValue
  OwnershipStartDateType: DateType
  OwnershipEndDateConfidenceType: ConfidenceType
  OwnershipEndDateConfidenceNote: String
  OwnershipEndDateConfidenceProbabilityValue: Float
  OwnershipEndDateConfidenceAssessmentAdditionalNotes: String
  OwnershipEndDateAdditionalNotes: String
  OwnershipEndDateValue: DateValue
  OwnershipEndDateType: DateType
  Owner: OrganisationOrPerson! @relationship(type: "Owner", direction: OUT)
  Owned: Organisation! @relationship(type: "Owned", direction: OUT)
}

type Organisation {
  DissolutionAssociatedLegalProcess: [LegalProcess!]!
    @relationship(type: "DissolutionAssociatedLegalProcess", direction: OUT)
  FormationDateConfidenceType: ConfidenceType
  FormationDateConfidenceNote: String
  FormationDateConfidenceProbabilityValue: Float
  FormationDateConfidenceAssessmentAdditionalNotes: String
  FormationDateAdditionalNotes: String
  FormationDateValue: DateValue
  FormationDateType: DateType
  AssociatedOrganisation: [Organisation!]!
    @relationship(type: "AssociatedOrganisation", direction: OUT)
  OrganisationName: String
  DissolutionDateConfidenceType: ConfidenceType
  DissolutionDateConfidenceNote: String
  DissolutionDateConfidenceProbabilityValue: Float
  DissolutionDateConfidenceAssessmentAdditionalNotes: String
  DissolutionDateAdditionalNotes: String
  DissolutionDateValue: DateValue
  DissolutionDateType: DateType
  AlternativeOrganisationName: String
  OrganisationDocumentedinSource: [Source!]!
    @relationship(type: "OrganisationDocumentedinSource", direction: OUT)
  OrganisationVIAFIdentifier: String
  OrganisationWikidataIdentifier: String
  OrganisationResearchNote: String
  OrganisationType: [OrganisationType!]
  OrganisationAdditionalNotes: String
  OrganisationWorkedFor: [OrganisationOrPerson!]!
    @relationship(type: "OrganisationWorkedFor", direction: OUT)
}

type Object {
  MadeFrom: MaterialTypes
  DocumentedIn: [Source!]! @relationship(type: "DocumentedIn", direction: OUT)
  HasDescription: String
  HasCatalogueIdentifier: String
  ObjectType: ObjectTypes
  HeldBy: OrganisationOrPerson! @relationship(type: "HeldBy", direction: OUT)
  CatalogueRecordURL: String
}

type Membership {
  MembershipEndDateConfidenceType: ConfidenceType
  MembershipEndDateConfidenceNote: String
  MembershipEndDateConfidenceProbabilityValue: Float
  MembershipEndDateConfidenceAssessmentAdditionalNotes: String
  MembershipEndDateAdditionalNotes: String
  MembershipEndDateValue: DateValue
  MembershipEndDateType: DateType
  MembershipType: MembershipType
  MembershipAdditionalNotes: String
  Member: Person! @relationship(type: "Member", direction: OUT)
  MemberofOrganisation: Organisation!
    @relationship(type: "MemberofOrganisation", direction: OUT)
  MembershipStartDateConfidenceType: ConfidenceType
  MembershipStartDateConfidenceNote: String
  MembershipStartDateConfidenceProbabilityValue: Float
  MembershipStartDateConfidenceAssessmentAdditionalNotes: String
  MembershipStartDateAdditionalNotes: String
  MembershipStartDateValue: DateValue
  MembershipStartDateType: DateType
}

type Marriage {
  MarriageEndDateConfidenceType: ConfidenceType
  MarriageEndDateConfidenceNote: String
  MarriageEndDateConfidenceProbabilityValue: Float
  MarriageEndDateConfidenceAssessmentAdditionalNotes: String
  MarriageEndDateAdditionalNotes: String
  MarriageEndDateValue: DateValue
  MarriageEndDateType: DateType
  Spouse: [Person!]! @relationship(type: "Spouse", direction: OUT)
  MarriageStartDateConfidenceType: ConfidenceType
  MarriageStartDateConfidenceNote: String
  MarriageStartDateConfidenceProbabilityValue: Float
  MarriageStartDateConfidenceAssessmentAdditionalNotes: String
  MarriageStartDateAdditionalNotes: String
  MarriageStartDateValue: DateValue
  MarriageStartDateType: DateType
}

type LegalProcess {
  Suer: OrganisationOrPerson! @relationship(type: "Suer", direction: OUT)
  Sued: OrganisationOrPerson! @relationship(type: "Sued", direction: OUT)
  LegalProcessStartDateConfidenceType: ConfidenceType
  LegalProcessStartDateConfidenceNote: String
  LegalProcessStartDateConfidenceProbabilityValue: Float
  LegalProcessStartDateConfidenceAssessmentAdditionalNotes: String
  LegalProcessStartDateAdditionalNotes: String
  LegalProcessStartDateValue: DateValue
  LegalProcessStartDateType: DateType
  LegalProcessType: TypesofLegalProcess
  LegalProcessEndDateConfidenceType: ConfidenceType
  LegalProcessEndDateConfidenceNote: String
  LegalProcessEndDateConfidenceProbabilityValue: Float
  LegalProcessEndDateConfidenceAssessmentAdditionalNotes: String
  LegalProcessEndDateAdditionalNotes: String
  LegalProcessEndDateValue: DateValue
  LegalProcessEndDateType: DateType
  Petitioner: [OrganisationOrPerson!]!
    @relationship(type: "Petitioner", direction: OUT)
  Prosecutor: OrganisationOrPerson!
    @relationship(type: "Prosecutor", direction: OUT)
  SentenceType: SentenceType
  Defendant: OrganisationOrPerson!
    @relationship(type: "Defendant", direction: OUT)
  CaseDescription: String
  LegalProcessName: String
}

type Inventing {
  InventedObjectType: ObjectTypes
  InventingAdditionalNotes: String
  Inventor: OrganisationOrPerson!
    @relationship(type: "Inventor", direction: OUT)
  InventingType: InventionTypes
  InventingStartDateConfidenceType: ConfidenceType
  InventingStartDateConfidenceNote: String
  InventingStartDateConfidenceProbabilityValue: Float
  InventingStartDateConfidenceAssessmentAdditionalNotes: String
  InventingStartDateAdditionalNotes: String
  InventingStartDateValue: DateValue
  InventingStartDateType: DateType
  InventingEndDateConfidenceType: ConfidenceType
  InventingEndDateConfidenceNote: String
  InventingEndDateConfidenceProbabilityValue: Float
  InventingEndDateConfidenceAssessmentAdditionalNotes: String
  InventingEndDateAdditionalNotes: String
  InventingEndDateValue: DateValue
  InventingEndDateType: DateType
}

type Exporting {
  ExportedTo: OrganisationOrPerson!
    @relationship(type: "ExportedTo", direction: OUT)
  ExportingStartDateConfidenceType: ConfidenceType
  ExportingStartDateConfidenceNote: String
  ExportingStartDateConfidenceProbabilityValue: Float
  ExportingStartDateConfidenceAssessmentAdditionalNotes: String
  ExportingStartDateAdditionalNotes: String
  ExportingStartDateValue: DateValue
  ExportingStartDateType: DateType
  ExportingEndDateConfidenceType: ConfidenceType
  ExportingEndDateConfidenceNote: String
  ExportingEndDateConfidenceProbabilityValue: Float
  ExportingEndDateConfidenceAssessmentAdditionalNotes: String
  ExportingEndDateAdditionalNotes: String
  ExportingEndDateValue: DateValue
  ExportingEndDateType: DateType
  ExportedObjectsofType: [ObjectTypes!]
  ExxportedSpecificObjects: [Object!]!
    @relationship(type: "ExxportedSpecificObjects", direction: OUT)
  ExportedBy: OrganisationOrPerson!
    @relationship(type: "ExportedBy", direction: OUT)
}

type Expedition {
  PlacesVisitedonExpedition: [Place!]!
    @relationship(type: "PlacesVisitedonExpedition", direction: OUT)
  ExpeditionCarriedOutBy: [OrganisationOrPerson!]!
    @relationship(type: "ExpeditionCarriedOutBy", direction: OUT)
  ExpeditionAdditionalNotes: String
  ExpeditionName: String
  ExpeditionStartDateConfidenceType: ConfidenceType
  ExpeditionStartDateConfidenceNote: String
  ExpeditionStartDateConfidenceProbabilityValue: Float
  ExpeditionStartDateConfidenceAssessmentAdditionalNotes: String
  ExpeditionStartDateAdditionalNotes: String
  ExpeditionStartDateValue: DateValue
  ExpeditionStartDateType: DateType
  ExhibitionEndDateConfidenceType: ConfidenceType
  ExhibitionEndDateConfidenceNote: String
  ExhibitionEndDateConfidenceProbabilityValue: Float
  ExhibitionEndDateConfidenceAssessmentAdditionalNotes: String
  ExhibitionEndDateAdditionalNotes: String
  ExhibitionEndDateValue: DateValue
  ExhibitionEndDateType: DateType
}

type Exhibition {
  ExhibitionEndDateConfidenceType: ConfidenceType
  ExhibitionEndDateConfidenceNote: String
  ExhibitionEndDateConfidenceProbabilityValue: Float
  ExhibitionEndDateConfidenceAssessmentAdditionalNotes: String
  ExhibitionEndDateAdditionalNotes: String
  ExhibitionEndDateValue: DateValue
  ExhibitionEndDateType: DateType
  ExhibitedWorkBy: [OrganisationOrPerson!]!
    @relationship(type: "ExhibitedWorkBy", direction: OUT)
  ExhibitionAdditionalNotes: String
  ExhibitionTookPlaceAt: [AddressOrPlace!]!
    @relationship(type: "ExhibitionTookPlaceAt", direction: OUT)
  ExhibitionName: String
  ExhibitionStartDateConfidenceType: ConfidenceType
  ExhibitionStartDateConfidenceNote: String
  ExhibitionStartDateConfidenceProbabilityValue: Float
  ExhibitionStartDateConfidenceAssessmentAdditionalNotes: String
  ExhibitionStartDateAdditionalNotes: String
  ExhibitionStartDateValue: DateValue
  ExhibitionStartDateType: DateType
}

type Employment {
  EmploymentStartDateConfidenceType: ConfidenceType
  EmploymentStartDateConfidenceNote: String
  EmploymentStartDateConfidenceProbabilityValue: Float
  EmploymentStartDateConfidenceAssessmentAdditionalNotes: String
  EmploymentStartDateAdditionalNotes: String
  EmploymentStartDateValue: DateValue
  EmploymentStartDateType: DateType
  EmploymentEndDateConfidenceType: ConfidenceType
  EmploymentEndDateConfidenceNote: String
  EmploymentEndDateConfidenceProbabilityValue: Float
  EmploymentEndDateConfidenceAssessmentAdditionalNotes: String
  EmploymentEndDateAdditionalNotes: String
  EmploymentEndDateValue: DateValue
  EmploymentEndDateType: DateType
  Employee: Person! @relationship(type: "Employee", direction: OUT)
  Employer: OrganisationOrPerson!
    @relationship(type: "Employer", direction: OUT)
}

type Education {
  EducatedPerson: Person! @relationship(type: "EducatedPerson", direction: OUT)
  Educator: Person! @relationship(type: "Educator", direction: OUT)
  EducationProvider: Organisation!
    @relationship(type: "EducationProvider", direction: OUT)
  EducationStartDateConfidenceType: ConfidenceType
  EducationStartDateConfidenceNote: String
  EducationStartDateConfidenceProbabilityValue: Float
  EducationStartDateConfidenceAssessmentAdditionalNotes: String
  EducationStartDateAdditionalNotes: String
  EducationStartDateValue: DateValue
  EducationStartDateType: DateType
  EducationEndDateConfidenceType: ConfidenceType
  EducationEndDateConfidenceNote: String
  EducationEndDateConfidenceProbabilityValue: Float
  EducationEndDateConfidenceAssessmentAdditionalNotes: String
  EducationEndDateAdditionalNotes: String
  EducationEndDateValue: DateValue
  EducationEndDateType: DateType
  EducatorRoleType: EducatorRoleTypes
  SubjectArea: [SubjectAreas!]
}

type ChronometerTrial {
  ChronometerTrialStartDateConfidenceType: ConfidenceType
  ChronometerTrialStartDateConfidenceNote: String
  ChronometerTrialStartDateConfidenceProbabilityValue: Float
  ChronometerTrialStartDateConfidenceAssessmentAdditionalNotes: String
  ChronometerTrialStartDateAdditionalNotes: String
  ChronometerTrialStartDateValue: DateValue
  ChronometerTrialStartDateType: DateType
  ChronometerTrialName: String
  ChronometerTrialEndDateConfidenceType: ConfidenceType
  ChronometerTrialEndDateConfidenceNote: String
  ChronometerTrialEndDateConfidenceProbabilityValue: Float
  ChronometerTrialEndDateConfidenceAssessmentAdditionalNotes: String
  ChronometerTrialEndDateAdditionalNotes: String
  ChronometerTrialEndDateValue: DateValue
  ChronometerTrialEndDateType: DateType
  TrialledChronometer: Object!
    @relationship(type: "TrialledChronometer", direction: OUT)
  ChronometerTrialTookPlaceAt: Place!
    @relationship(type: "ChronometerTrialTookPlaceAt", direction: OUT)
  ChronometerTrialOccurredonExpedition: Expedition!
    @relationship(type: "ChronometerTrialOccurredonExpedition", direction: OUT)
}

type BusinessAppointment {
  BusinessAppointmentEndDateConfidenceType: ConfidenceType
  BusinessAppointmentEndDateConfidenceNote: String
  BusinessAppointmentEndDateConfidenceProbabilityValue: Float
  BusinessAppointmentEndDateConfidenceAssessmentAdditionalNotes: String
  BusinessAppointmentEndDateAdditionalNotes: String
  BusinessAppointmentEndDateValue: DateValue
  BusinessAppointmentEndDateType: DateType
  BusinessAppointmentAdditionalNotes: String
  BusinessAppointmentMakerAppointed: OrganisationOrPerson!
    @relationship(type: "BusinessAppointmentMakerAppointed", direction: OUT)
  BusinessAppointmentMadeBy: OrganisationOrPerson!
    @relationship(type: "BusinessAppointmentMadeBy", direction: OUT)
  BusinessAppointmentStartDateConfidenceType: ConfidenceType
  BusinessAppointmentStartDateConfidenceNote: String
  BusinessAppointmentStartDateConfidenceProbabilityValue: Float
  BusinessAppointmentStartDateConfidenceAssessmentAdditionalNotes: String
  BusinessAppointmentStartDateAdditionalNotes: String
  BusinessAppointmentStartDateValue: DateValue
  BusinessAppointmentStartDateType: DateType
}

type Award {
  AwardedBy: ExhibitionOrOrganisationOrPerson!
    @relationship(type: "AwardedBy", direction: OUT)
  AwardName: String
  AwardedTo: OrganisationOrPerson!
    @relationship(type: "AwardedTo", direction: OUT)
  AwardedFor: ChronometerTrial!
    @relationship(type: "AwardedFor", direction: OUT)
  AwardType: AwardTypes
  AwardDateConfidenceType: ConfidenceType
  AwardDateConfidenceNote: String
  AwardDateConfidenceProbabilityValue: Float
  AwardDateConfidenceAssessmentAdditionalNotes: String
  AwardDateAdditionalNotes: String
  AwardDateValue: DateValue
  AwardDateType: DateType
}

type AtAddress {
  AtAddressEndDateConfidenceType: ConfidenceType
  AtAddressEndDateConfidenceNote: String
  AtAddressEndDateConfidenceProbabilityValue: Float
  AtAddressEndDateConfidenceAssessmentAdditionalNotes: String
  AtAddressEndDateAdditionalNotes: String
  AtAddressEndDateValue: DateValue
  AtAddressEndDateType: DateType
  OccupiedAddress: Address!
    @relationship(type: "OccupiedAddress", direction: OUT)
  AtAddressStartDateConfidenceType: ConfidenceType
  AtAddressStartDateConfidenceNote: String
  AtAddressStartDateConfidenceProbabilityValue: Float
  AtAddressStartDateConfidenceAssessmentAdditionalNotes: String
  AtAddressStartDateAdditionalNotes: String
  AtAddressStartDateValue: DateValue
  AtAddressStartDateType: DateType
  AddressFunction: [AddressFunction!]
  InvolvedOccupants: [OrganisationOrPerson!]!
    @relationship(type: "InvolvedOccupants", direction: OUT)
  AtAddressAdditionalNotes: String
}

type Apprenticeship {
  Master: Person! @relationship(type: "Master", direction: OUT)
  ApprenticeshipInvolvedGuild: Organisation!
    @relationship(type: "ApprenticeshipInvolvedGuild", direction: OUT)
  TranslatedDateConfidenceType: ConfidenceType
  TranslatedDateConfidenceNote: String
  TranslatedDateConfidenceProbabilityValue: Float
  TranslatedDateConfidenceAssessmentAdditionalNotes: String
  TranslatedDateAdditionalNotes: String
  TranslatedDateValue: DateValue
  TranslatedDateType: DateType
  ApprenticeshipMoneyPaidBy: [OrganisationOrPerson!]!
    @relationship(type: "ApprenticeshipMoneyPaidBy", direction: OUT)
  NewGuild: Organisation! @relationship(type: "NewGuild", direction: OUT)
  BoundDateConfidenceType: ConfidenceType
  BoundDateConfidenceNote: String
  BoundDateConfidenceProbabilityValue: Float
  BoundDateConfidenceAssessmentAdditionalNotes: String
  BoundDateAdditionalNotes: String
  BoundDateValue: DateValue
  BoundDateType: DateType
  FreedFromBoundsDateConfidenceType: ConfidenceType
  FreedFromBoundsDateConfidenceNote: String
  FreedFromBoundsDateConfidenceProbabilityValue: Float
  FreedFromBoundsDateConfidenceAssessmentAdditionalNotes: String
  FreedFromBoundsDateAdditionalNotes: String
  FreedFromBoundsDateValue: DateValue
  FreedFromBoundsDateType: DateType
  TurnedOverDateConfidenceType: ConfidenceType
  TurnedOverDateConfidenceNote: String
  TurnedOverDateConfidenceProbabilityValue: Float
  TurnedOverDateConfidenceAssessmentAdditionalNotes: String
  TurnedOverDateAdditionalNotes: String
  TurnedOverDateValue: DateValue
  TurnedOverDateType: DateType
  FreedCategory: FreedCategory
  FreedMode: FreedMode
  ApprenticeshipAdditionalNotes: String
  NewMaster: Person! @relationship(type: "NewMaster", direction: OUT)
  Apprentice: Person! @relationship(type: "Apprentice", direction: OUT)
}

type Agenting {
  Client: OrganisationOrPerson! @relationship(type: "Client", direction: OUT)
  AgentforObjectsofType: [ObjectTypes!]
  AgentingStartDateConfidenceType: ConfidenceType
  AgentingStartDateConfidenceNote: String
  AgentingStartDateConfidenceProbabilityValue: Float
  AgentingStartDateConfidenceAssessmentAdditionalNotes: String
  AgentingStartDateAdditionalNotes: String
  AgentingStartDateValue: DateValue
  AgentingStartDateType: DateType
  AgentforSpecificObjects: [Object!]!
    @relationship(type: "AgentforSpecificObjects", direction: OUT)
  AgentingEndDateConfidenceType: ConfidenceType
  AgentingEndDateConfidenceNote: String
  AgentingEndDateConfidenceProbabilityValue: Float
  AgentingEndDateConfidenceAssessmentAdditionalNotes: String
  AgentingEndDateAdditionalNotes: String
  AgentingEndDateValue: DateValue
  AgentingEndDateType: DateType
  Agent: OrganisationOrPerson! @relationship(type: "Agent", direction: OUT)
}

type Advertising {
  AdvertisingDateConfidenceType: ConfidenceType
  AdvertisingDateConfidenceNote: String
  AdvertisingDateConfidenceProbabilityValue: Float
  AdvertisingDateConfidenceAssessmentAdditionalNotes: String
  AdvertisingDateAdditionalNotes: String
  AdvertisingDateValue: DateValue
  AdvertisingDateType: DateType
  AdvertisedObjectsofMaterials: [MaterialTypes!]
  AdvertisedObjectsforuseinOccupations: [OccupationTypes!]
  ProducedAdvertisement: Source!
    @relationship(type: "ProducedAdvertisement", direction: OUT)
  AdvertisedSpecificObjects: [Object!]!
    @relationship(type: "AdvertisedSpecificObjects", direction: OUT)
  AdvertisingAdditionalNotes: String
  AdvertisedObjectsofTypes: [ObjectTypes!]
  AdvertisedObjectsinScientificDomains: [SubjectAreas!]
  AdvertisedMaker: [OrganisationOrPerson!]!
    @relationship(type: "AdvertisedMaker", direction: OUT)
  AdvertisedMakerOccupation: [OccupationTypes!]
}

type Address {
  VillageTownCity: Place! @relationship(type: "VillageTownCity", direction: OUT)
  AddressCode: String
  AddressNote: String
  GeocodingNote: String
  AreaName: String
  BuildingName: String
  StreetAddress: String
  GeocodedPlace: Place! @relationship(type: "GeocodedPlace", direction: OUT)
}

type EventwithDateRange {
  EventEndDateConfidenceType: ConfidenceType
  EventEndDateConfidenceNote: String
  EventEndDateConfidenceProbabilityValue: Float
  EventEndDateConfidenceAssessmentAdditionalNotes: String
  EventEndDateAdditionalNotes: String
  EventEndDateValue: DateValue
  EventEndDateType: DateType
  EventStartDateConfidenceType: ConfidenceType
  EventStartDateConfidenceNote: String
  EventStartDateConfidenceProbabilityValue: Float
  EventStartDateConfidenceAssessmentAdditionalNotes: String
  EventStartDateAdditionalNotes: String
  EventStartDateValue: DateValue
  EventStartDateType: DateType
}

type DateValue {
  DateAdditionalNotes: String
  DateValue: DateValue
  DateType: DateType
  DateConfidenceProbabilityValue: Float
  DateConfidenceNote: String
  DateConfidenceType: ConfidenceType
  DateConfidenceAssessmentAdditionalNotes: String
}

type ConfidenceAssessment {
  ConfidenceAssessmentAdditionalNotes: String
  ConfidenceNote: String
  ConfidenceProbabilityValue: Float
  ConfidenceType: ConfidenceType
}
